import type { Sentence } from './types';

/**
 * Decodable sentences for the sentence→picture mechanic.
 * Sentences marked "book" are verbatim from Evie's book pages.
 *
 * Picture cards are emoji compositions. The correct picture requires reading
 * the WHOLE sentence — distractors are near-misses (same subject different
 * object, same object different subject, or a missing part).
 */

const S = (
  id: string,
  text: string,
  wordIds: string[],
  lesson: number,
  correctEmoji: string,
  distractorEmojis: [string, string],
  rereadPrompt?: string,
): Sentence => ({
  id,
  text,
  wordIds,
  lesson,
  correctEmoji,
  distractorEmojis,
  ...(rereadPrompt ? { rereadPrompt } : {}),
});

export const SENTENCES: Sentence[] = [
  // ---- Level 1 (book lessons 1–9; several verbatim from the book) ----
  S('s001', 'Max sat.', ['max', 'sat'], 4, '👦🪑', ['👦🏃', '👧🪑'], 'Read it again nice and smooth.'),
  S('s002', 'Tam has ham.', ['tam', 'has', 'ham'], 3, '👧🍖', ['👧👒', '👦🍖'], 'Read it like you are very hungry!'),
  S('s003', 'A man has a hat.', ['a', 'man', 'has', 'a', 'hat'], 3, '👨👒', ['👨👜', '👩👒']),
  S('s004', 'Sam has an ax.', ['sam', 'has', 'an', 'ax'], 3, '👦🪓', ['👦🐜', '👧🪓'], 'Read it in a big strong voice!'),
  S('s005', 'Dad had a hat.', ['dad', 'had', 'a', 'hat'], 4, '👨👒', ['👨🪭', '👧👒']),
  S('s006', 'Max had wax and sand.', ['max', 'had', 'wax', 'and', 'sand'], 4, '👦🕯️🏖️', ['👦🕯️', '👦🏖️'], 'Read it again nice and smooth.'),
  S('s007', 'Sam was sad.', ['sam', 'was', 'sad'], 5, '👦😢', ['👦😀', '👧😢'], 'Read it in a sad, sad voice.'),
  S('s008', 'Dan ran fast.', ['dan', 'ran', 'fast'], 8, '👦💨', ['👦😴', '👧💨'], 'Read it super fast!'),
  S('s009', 'A cat sat.', ['a', 'cat', 'sat'], 7, '🐱🪑', ['🐱🏃', '🐶🪑']),
  S('s010', 'A man has a van.', ['a', 'man', 'has', 'a', 'van'], 8, '👨🚐', ['👨🚚', '👩🚐']),

  // ---- Level 2 (book lessons 10–17) ----
  S('s011', 'Bill hid in a box.', ['bill', 'hid', 'in', 'a', 'box'], 14, '👦📦', ['👦🛏️', '👧📦'], 'Read it in a whisper, like hiding!'),
  S('s012', 'A dog sat on a log.', ['a', 'dog', 'sat', 'on', 'a', 'log'], 14, '🐶🪵', ['🐶🪨', '🐱🪵']),
  S('s013', 'A hen has an egg.', ['a', 'hen', 'has', 'an', 'egg'], 13, '🐔🥚', ['🐔🪺', '🦆🥚'], 'Read it like a clucky hen!'),
  S('s014', 'A bug is in a cup.', ['a', 'bug', 'is', 'in', 'a', 'cup'], 14, '🐛☕', ['🐛📦', '🐟☕']),
  S('s015', 'A fox ran up a hill.', ['a', 'fox', 'ran', 'up', 'a', 'hill'], 14, '🦊⛰️', ['🦊🪵', '🐶⛰️'], 'Read it like a sneaky fox.'),
  S('s016', 'A duck can quack.', ['a', 'duck', 'can', 'quack'], 14, '🦆💬', ['🦆😴', '🐔💬'], 'Read it like a silly duck!'),
  S('s017', 'Mom got a pup.', ['mom', 'got', 'a', 'pup'], 14, '👩🐕', ['👩🐱', '👦🐕'], 'Read it like it is the best gift ever!'),
  S('s018', 'Jill can kick.', ['jill', 'can', 'kick'], 13, '👧⚽', ['👧🤸', '👦⚽']),
  S('s019', 'A pup dug in the mud.', ['a', 'pup', 'dug', 'in', 'the', 'mud'], 19, '🐕🟤', ['🐕🛁', '🐱🟤'], 'Read it like a messy puppy!'),
  S('s020', 'The sun is hot.', ['the', 'sun', 'is', 'hot'], 19, '☀️🔥', ['☀️💧', '🌙🔥']),

  // ---- Level 3 (book lessons 18–30; several verbatim from the book) ----
  S('s021', 'Philip is sick, ill, and sad.', ['philip', 'is', 'sick', 'ill', 'and', 'sad'], 18, '👦🤒', ['👦😀', '👧🤒'], 'Read it in a poor sick voice.'),
  S('s022', 'Sick Philip was fed in bed.', ['sick', 'philip', 'was', 'fed', 'in', 'bed'], 18, '👦🤒🛏️', ['👦🤒🛁', '👧🤒🛏️']),
  S('s023', 'Phil will miss his pet cat.', ['phil', 'will', 'miss', 'his', 'pet', 'cat'], 18, '👦💭🐱', ['👦💭🐶', '👧💭🐱'], 'Read it in a missing-you voice.'),
  S('s024', 'Bill hid his quill in a big sack.', ['bill', 'hid', 'his', 'quill', 'in', 'a', 'big', 'sack'], 13, '👦🪶🛍️', ['👦🪶📦', '👦🖊️🛍️'], 'Read it in a whisper, like a secret.'),
  S('s025', 'Quick, Jill, fix it!', ['quick', 'jill', 'fix', 'it'], 13, '👧🔧💨', ['👧🧹', '👦🔧'], 'Read it like an emergency!'),
  S('s026', 'The fish is in the dish.', ['the', 'fish', 'is', 'in', 'the', 'dish'], 26, '🐟🍽️', ['🐟📦', '🐤🍽️']),
  S('s027', 'A chick is in the shell.', ['a', 'chick', 'is', 'in', 'the', 'shell'], 28, '🐤🐚', ['🐤🪺', '🐟🐚'], 'Read it like a tiny chick — peep peep!'),
  S('s028', 'Wash the dog in the bath.', ['wash', 'the', 'dog', 'in', 'the', 'bath'], 26, '🐶🛁🧼', ['🐶🛏️', '🐱🛁'], 'Read it like a bossy big sister.'),
  S('s029', 'The ship has a red flag.', ['the', 'ship', 'has', 'a', 'red', 'flag'], 26, '🚢🚩', ['🚢⬛', '🛶🚩']),
  S('s030', 'Mom can chop the log with an ax.', ['mom', 'can', 'chop', 'the', 'log', 'with', 'an', 'ax'], 28, '👩🪓🪵', ['👩🪓🐟', '👦🪓🪵'], 'Read it in a big strong voice!'),
  S('s031', 'The moth is on the path.', ['the', 'moth', 'is', 'on', 'the', 'path'], 19, '🦋🛤️', ['🦋🛁', '🐟🛤️']),
  S('s032', 'Quick, get the cat, Philip!', ['quick', 'get', 'the', 'cat', 'philip'], 19, '👦🐱💨', ['👦🐶💨', '👧🐱']),

  // ---- Level 4 (book lessons 31–45) ----
  S('s033', 'A frog can jump and swim.', ['a', 'frog', 'can', 'jump', 'and', 'swim'], 31, '🐸🤸🏊', ['🐸😴', '🐟🤸'], 'Read it like a bouncy frog!'),
  S('s034', 'The king can sing a song.', ['the', 'king', 'can', 'sing', 'a', 'song'], 37, '🤴🎤🎵', ['🤴😴', '👸🎤🎵'], 'Sing it like a king!'),
  S('s035', 'Tam and Max want ham.', ['tam', 'and', 'max', 'want', 'ham'], 41, '👧👦🍖', ['👧🍖', '👧👦🥚']),
  S('s036', 'Her wand is pink.', ['her', 'wand', 'is', 'pink'], 43, '🪄🩷', ['🪄🟥', '💍🩷'], 'Read it like a magic spell!'),
  S('s037', 'Max got a pink drink.', ['max', 'got', 'a', 'pink', 'drink'], 43, '👦🩷🥤', ['👦☕', '👧🩷🥤']),
  S('s038', 'Mom and Dad had lunch.', ['mom', 'and', 'dad', 'had', 'lunch'], 43, '👩👨🥪', ['👩🥪', '👨👦🥪']),
  S('s039', 'A bug sat on a branch.', ['a', 'bug', 'sat', 'on', 'a', 'branch'], 43, '🐛🌿', ['🐛🪨', '🐜🌿']),
  S('s040', 'The gift is soft.', ['the', 'gift', 'is', 'soft'], 45, '🎁🧸', ['🎁🪨', '📦🧸']),
  S('s041', 'Sam can lift the raft.', ['sam', 'can', 'lift', 'the', 'raft'], 45, '👦🏋️🛶', ['👦🏋️📦', '👧🏋️🛶'], 'Read it in a big strong voice!'),

  // ---- Level 5 (book lessons 46–65) ----
  S('s042', 'The elf hid on the shelf.', ['the', 'elf', 'hid', 'on', 'the', 'shelf'], 49, '🧝📚', ['🧝🛏️', '👦📚'], 'Read it in a tiny elf voice!'),
  S('s043', 'Dan and Jill walk and talk.', ['dan', 'and', 'jill', 'walk', 'and', 'talk'], 49, '👦👧🚶💬', ['👦👧🏃', '👦👧😴']),
  S('s044', 'The pup can fetch the hat.', ['the', 'pup', 'can', 'fetch', 'the', 'hat'], 51, '🐕👒💨', ['🐕🧦', '🐱👒'], 'Read it like an excited puppy!'),
  S('s045', 'The sun can melt it.', ['the', 'sun', 'can', 'melt', 'it'], 51, '☀️🫠', ['☀️🧊', '🌙🫠']),
  S('s046', 'One duck sat on the bridge.', ['one', 'duck', 'sat', 'on', 'the', 'bridge'], 53, '🦆🌉', ['🦆🪵', '🐔🌉']),
  S('s047', 'The prince can dance and sing.', ['the', 'prince', 'can', 'dance', 'and', 'sing'], 53, '🤴🕺🎵', ['🤴😴', '👸💃🎵'], 'Read it like a fancy prince!'),
  S('s048', 'Tam and Sam had fudge.', ['tam', 'and', 'sam', 'had', 'fudge'], 53, '👧👦🍫', ['👧🍫', '👧👦🍪']),
  S('s049', 'The clock on the shelf is black.', ['the', 'clock', 'on', 'the', 'shelf', 'is', 'black'], 55, '🕐⬛', ['🕐🟥', '🔔⬛']),
  S('s050', 'Her dress is fresh and pink.', ['her', 'dress', 'is', 'fresh', 'and', 'pink'], 57, '👗🩷', ['👗⬛', '👖🩷']),
  S('s051', 'Smell the fresh spring grass.', ['smell', 'the', 'fresh', 'spring', 'grass'], 61, '👃🌿🌸', ['👃🍫', '👀🌿'], 'Take a big sniff as you read!'),

  // ---- Level 6 (book lessons 66–77) ----
  S('s052', 'The snake is in the lake.', ['the', 'snake', 'is', 'in', 'the', 'lake'], 66, '🐍🏞️', ['🐍🏖️', '🐊🏞️'], 'Read it in a hissy snake voice!'),
  S('s053', 'Mom made a cake.', ['mom', 'made', 'a', 'cake'], 66, '👩🎂', ['👩🧁', '👧🎂']),
  S('s054', 'The whale made a big wave.', ['the', 'whale', 'made', 'a', 'big', 'wave'], 66, '🐋🌊', ['🐋😴', '🐟🌊'], 'Read it in a big whale voice!'),
  S('s055', 'Max and Tam are brave.', ['max', 'and', 'tam', 'are', 'brave'], 66, '👦👧💪', ['👦👧🙈', '👦💪']),
  S('s056', 'The train is in the rain.', ['the', 'train', 'is', 'in', 'the', 'rain'], 70, '🚂🌧️', ['🚂☀️', '🚗🌧️']),
  S('s057', 'The snail said, "Wait!"', ['the', 'snail', 'said', 'wait'], 70, '🐌✋', ['🐌💤', '🐢✋'], 'Read it slooowly like a snail.'),
  S('s058', 'Jill can play all day.', ['jill', 'can', 'play', 'all', 'day'], 72, '👧🛝', ['👧😴', '👦🛝']),
  S('s059', 'The ship can sail away.', ['the', 'ship', 'can', 'sail', 'away'], 72, '🚢💨', ['🚢⚓', '⛵💨']),
  S('s060', 'A hawk sat on a branch at dawn.', ['a', 'hawk', 'sat', 'on', 'a', 'branch', 'at', 'dawn'], 76, '🦅🌿🌅', ['🦅🌿🌙', '🦆🌿🌅']),
  S('s061', 'Dad can draw a whale.', ['dad', 'can', 'draw', 'a', 'whale'], 76, '👨🖍️🐋', ['👨🖍️🐍', '👧🖍️🐋']),

  // ---- Level 7 (book lessons 78–95) ----
  S('s062', 'The star is far, far away.', ['the', 'star', 'is', 'far', 'far', 'away'], 80, '⭐🌌', ['🌙🌌', '⭐🏠'], 'Read it in a dreamy voice.'),
  S('s063', 'The queen fed the sheep.', ['the', 'queen', 'fed', 'the', 'sheep'], 82, '👸🐑', ['👸🐄', '🤴🐑'], 'Read it in a royal voice!'),
  S('s064', 'He has a red car.', ['he', 'has', 'a', 'red', 'car'], 84, '👨🟥🚗', ['👨🚐', '👩🟥🚗']),
  S('s065', 'She can see the green tree.', ['she', 'can', 'see', 'the', 'green', 'tree'], 84, '👧👀🌳', ['👧👀🌵', '👦👀🌳']),
  S('s066', 'The shark is in the dark sea.', ['the', 'shark', 'is', 'in', 'the', 'dark', 'sea'], 86, '🦈🌊🌑', ['🦈🌊☀️', '🐬🌊🌑'], 'Read it in a deep, dark voice.'),
  S('s067', 'We can eat a peach on the beach.', ['we', 'can', 'eat', 'a', 'peach', 'on', 'the', 'beach'], 86, '🍑🏖️😋', ['🍑🏠', '🍎🏖️']),
  S('s068', 'Pete had a dream.', ['pete', 'had', 'a', 'dream'], 87, '👦💭', ['👦📖', '👧💭'], 'Read it in a sleepy voice.'),
  S('s069', 'My pie is sweet.', ['my', 'pie', 'is', 'sweet'], 92, '🥧🍭', ['🥧🌶️', '🍕🍭']),
  S('s070', 'A fly is in the sky.', ['a', 'fly', 'is', 'in', 'the', 'sky'], 92, '🪰☁️', ['🪰🏠', '🐦☁️']),
  S('s071', 'Mom can buy a bun and milk.', ['mom', 'can', 'buy', 'a', 'bun', 'and', 'milk'], 94, '👩🥯🥛', ['👩🥯', '👩🥛🍞']),

  // ---- Level 8 (book lessons 96–115) ----
  S('s072', 'She can ride a bike.', ['she', 'can', 'ride', 'a', 'bike'], 96, '👧🚲', ['👧🛴', '👦🚲'], 'Read it fast like a race!'),
  S('s073', 'My kite can fly high.', ['my', 'kite', 'can', 'fly', 'high'], 98, '🪁☁️', ['🪁🌳', '🎈☁️']),
  S('s074', 'The light is bright at night.', ['the', 'light', 'is', 'bright', 'at', 'night'], 98, '💡🌙✨', ['💡🌅', '🕯️🌙']),
  S('s075', 'The dog dug up a bone.', ['the', 'dog', 'dug', 'up', 'a', 'bone'], 103, '🐶🦴', ['🐶🥾', '🐱🦴'], 'Read it like a happy dog!'),
  S('s076', 'The goat is on the boat.', ['the', 'goat', 'is', 'on', 'the', 'boat'], 105, '🐐🛥️', ['🐐🚂', '🐄🛥️'], 'Read it like a silly goat!'),
  S('s077', 'Look at the moon.', ['look', 'at', 'the', 'moon'], 107, '👀🌕', ['👀☀️', '👀⭐'], 'Read it in a hushed night voice.'),
  S('s078', 'A cow can shout out loud.', ['a', 'cow', 'can', 'shout', 'out', 'loud'], 109, '🐄📣', ['🐄😴', '🐖📣'], 'Shout it out — MOO!'),
  S('s079', 'The boy has a blue toy.', ['the', 'boy', 'has', 'a', 'blue', 'toy'], 113, '👦🟦🧸', ['👦🟥🧸', '👧🟦🧸']),
  S('s080', 'The cute mule ate the fruit.', ['the', 'cute', 'mule', 'ate', 'the', 'fruit'], 113, '🫏🍉', ['🫏🌿', '🐴🍉']),
  S('s081', 'A rose grew at home.', ['a', 'rose', 'grew', 'at', 'home'], 115, '🌹🏠', ['🌻🏠', '🌹⛺']),

  // ---- Level 9 (book lessons 116–120) ----
  S('s082', 'The earth is my home.', ['the', 'earth', 'is', 'my', 'home'], 116, '🌍🏠', ['🌕🏠', '🌍🚀'], 'Read it in a proud voice!'),
  S('s083', 'A little bird sat on the girl.', ['a', 'little', 'bird', 'sat', 'on', 'the', 'girl'], 117, '🐦👧', ['🐦🌳', '🦋👧'], 'Read it in a tiny bird voice!'),
  S('s084', 'The turtle is purple.', ['the', 'turtle', 'is', 'purple'], 117, '🐢🟪', ['🐢🟩', '🐸🟪'], 'Read it slooowly like a turtle.'),
  S('s085', 'The lamb is little and sweet.', ['the', 'lamb', 'is', 'little', 'and', 'sweet'], 119, '🐑💕', ['🐐💕', '🐑😴']),
  S('s086', 'Light the candle at night.', ['light', 'the', 'candle', 'at', 'night'], 117, '🕯️🌙', ['🕯️☀️', '💡🌙'], 'Read it in a soft bedtime voice.'),
  S('s087', 'The girl had a special day.', ['the', 'girl', 'had', 'a', 'special', 'day'], 118, '👧🎉', ['👧😢', '👦🎉']),
  S('s088', 'She can write with a pen.', ['she', 'can', 'write', 'with', 'a', 'pen'], 119, '👧✍️', ['👧📖', '👦✍️']),
  S('s089', 'The knight had corn on a fork.', ['the', 'knight', 'had', 'corn', 'on', 'a', 'fork'], 119, '🛡️🌽🍴', ['🛡️🥧🍴', '🤴🌽🍴'], 'Read it like a noble knight!'),

  // ---- Verbatim book sentences (lessons 21-120), transcribed pages ----
  S('s090', 'Is the fox in the box?', ['is', 'the', 'fox', 'in', 'the', 'box'], 21, '🦊📦', ['🦊🛏️', '🐶📦'], 'Read it like a big question — is it, or isn\'t it?'),
  S('s091', 'Quick, Bob, get that mop.', ['quick', 'bob', 'get', 'that', 'mop'], 21, '👦🧹', ['👦🪣', '👧🧹'], 'Read it super fast — quick, quick, quick!'),
  S('s092', 'Quick son, jog on the path.', ['quick', 'son', 'jog', 'on', 'the', 'path'], 21, '🏃🛤️', ['🚶🛤️', '🏃🏖️']),
  S('s093', 'Dad\'s mop', ['dad', 'mop'], 22, '👨🧹', ['👩🧹', '👨🪣']),
  S('s094', 'Mom\'s van', ['mom', 'van'], 22, '👩🚐', ['👨🚐', '👩🚗'], 'Read it, then go beep beep like the van!'),
  S('s095', 'Jill\'s lock', ['jill', 'lock'], 22, '👧🔒', ['👧🔑', '👦🔒']),
  S('s096', 'Mom\'s hen has ten big eggs.', ['mom', 'hen', 'has', 'ten', 'big', 'eggs'], 23, '🐔🥚', ['🐔🐣', '🦆🥚'], 'Read it like a proud clucking hen!'),
  S('s097', 'The foxes sit in the boxes.', ['the', 'foxes', 'sit', 'in', 'the', 'boxes'], 23, '🦊🦊📦', ['🐱🐱📦', '🦊🦊🌳']),
  S('s098', 'Pam\'s pet is a big pig.', ['pam', 'pet', 'is', 'a', 'big', 'pig'], 23, '👧🐷', ['👧🐶', '👦🐷'], 'Read it with a big piggy snort — oink!'),
  S('s099', 'Jack\'s dog dug in the wet mud and had fun!', ['jack', 'dog', 'dug', 'in', 'the', 'wet', 'mud', 'and', 'had', 'fun'], 24, '🐶🕳️💦', ['🐶🛁💦', '🐱🕳️💦'], 'Read it with a happy, muddy bark!'),
  S('s100', 'Jack put the dog in the tub.', ['jack', 'put', 'the', 'dog', 'in', 'the', 'tub'], 24, '👦🐶🛁', ['👦🐱🛁', '👦🐶🛏️']),
  S('s101', 'Can the dog run up the hill?', ['can', 'the', 'dog', 'run', 'up', 'the', 'hill'], 24, '🐶⛰️', ['🐶🏠', '🐱⛰️'], 'Read it while huffing up a big, big hill!'),
  S('s102', 'Jill dashes up the hill in a rush.', ['jill', 'dashes', 'up', 'the', 'hill', 'in', 'a', 'rush'], 26, '👧💨⛰️', ['👦💨⛰️', '👧💨🏖️'], 'Read it super fast, like you\'re in a rush!'),
  S('s103', 'Put the shells and the fish in the big red ship.', ['put', 'the', 'shells', 'and', 'the', 'fish', 'in', 'the', 'big', 'red', 'ship'], 26, '🐚🐟🚢', ['🐚🐟🚗', '🐚🦀🚢']),
  S('s104', 'Josh\'s mop is in the shed.', ['josh', 'mop', 'is', 'in', 'the', 'shed'], 26, '🧹🛖', ['🪣🛖', '🧹🏠']),
  S('s105', 'Jan, wash the shells in the shack.', ['jan', 'wash', 'the', 'shells', 'in', 'the', 'shack'], 27, '👧🧼🐚', ['👧🧼🐟', '👦🧼🐚'], 'Read it like a bossy big sister!'),
  S('s106', 'Shut the boxes and lock them up.', ['shut', 'the', 'boxes', 'and', 'lock', 'them', 'up'], 27, '📦🔒', ['📦🔑', '🧺🔒']),
  S('s107', 'The red hen and the chicks sit in the hen box.', ['the', 'red', 'hen', 'and', 'the', 'chicks', 'sit', 'in', 'the', 'hen', 'box'], 28, '🐔🐤📦', ['🐔🥚📦', '🐔🐤🌳'], 'Read it with a tiny cheep-cheep like a chick!'),
  S('s108', 'Mom and Dad can chat on the big deck on the ship.', ['mom', 'and', 'dad', 'can', 'chat', 'on', 'the', 'big', 'deck', 'on', 'the', 'ship'], 28, '👩👨🚢', ['👩👨🏠', '👩👦🚢']),
  S('s109', 'Jill, check the cat\'s dish.', ['jill', 'check', 'the', 'cat', 'dish'], 28, '👧🐱🥣', ['👧🐶🥣', '👦🐱🥣']),
  S('s110', 'When can Jan\'s cat whiff the fish?', ['when', 'can', 'jan', 'cat', 'whiff', 'the', 'fish'], 30, '🐱👃🐟', ['🐱👃🌸', '🐶👃🐟'], 'Read it, then take a big sniff — sniff sniff!'),
  S('s111', 'Which fish is in the cat\'s dish?', ['which', 'fish', 'is', 'in', 'the', 'cat', 'dish'], 30, '🐱🥣🐟', ['🐱🥣🦴', '🐶🥣🐟'], 'Read it like a curious kitty — which one?'),
  S('s112', 'Mom can whip up a fish dish in the big hot pot.', ['mom', 'can', 'whip', 'up', 'a', 'fish', 'dish', 'in', 'the', 'big', 'hot', 'pot'], 30, '👩🐟🍲', ['👨🐟🍲', '👩🍗🍲']),
  S('s113', 'Which dish is the cat\'s?', ['which', 'dish', 'is', 'the', 'cat'], 31, '🐱🍽️', ['🐶🍽️', '🐱🛏️']),
  S('s114', 'The pig has a chill.', ['the', 'pig', 'has', 'a', 'chill'], 31, '🐷🥶', ['🐶🥶', '🐷🔥']),
  S('s115', 'The hen had six chicks in the box.', ['the', 'hen', 'had', 'six', 'chicks', 'in', 'the', 'box'], 31, '🐔🐥📦', ['🐔🐥🛏️', '🐱🐥📦'], 'Read it in a peep-peep chick voice!'),
  S('s116', 'Is it mom\'s pan? It\'s mom\'s pan.', ['is', 'it', 'mom', 'pan', 'it', 'mom', 'pan'], 32, '👩🍳', ['👨🍳', '👩🥄']),
  S('s117', 'Can the pig run? The pig can\'t run.', ['can', 'the', 'pig', 'run', 'the', 'pig', 'can\'t', 'run'], 32, '🐷🚫🏃', ['🐷🏃', '🐶🚫🏃'], 'Ask the question, then answer like you\'re really sure!'),
  S('s118', 'Let\'s not rush, Jill. Jill didn\'t rush.', ['let', 'not', 'rush', 'jill', 'jill', 'didn\'t', 'rush'], 32, '👧🐢', ['👧🏃', '👦🐢']),
  S('s119', 'Pam\'s camel sat on the cactus!', ['pam', 'camel', 'sat', 'on', 'the', 'cactus'], 34, '🐫🌵', ['🐫🪑', '🐴🌵'], 'Read it with a big OUCH at the end!'),
  S('s120', 'Dad can pack a picnic basket for the visit.', ['dad', 'can', 'pack', 'a', 'picnic', 'basket', 'for', 'the', 'visit'], 34, '👨🧺', ['👨🎒', '👩🧺']),
  S('s121', 'The sunset was sudden and vivid.', ['the', 'sunset', 'was', 'sudden', 'and', 'vivid'], 34, '🌇✨', ['🌃✨', '🌇🌧️'], 'Read it like you just saw something amazing!'),
  S('s122', 'Call Patrick at the mall.', ['call', 'patrick', 'at', 'the', 'mall'], 35, '📞👦🏬', ['📞👦🏠', '✉️👦🏬'], 'Read it like you\'re talking on the phone!'),
  S('s123', 'Pam has all the rabbits in the tall basket.', ['pam', 'has', 'all', 'the', 'rabbits', 'in', 'the', 'tall', 'basket'], 35, '👧🐰🧺', ['👧🐱🧺', '👧🐰📦']),
  S('s124', 'Mom and Dad sang the long song.', ['mom', 'and', 'dad', 'sang', 'the', 'long', 'song'], 37, '👩👨🎶', ['👩👨📖', '👧👦🎶'], 'Sing it instead of reading it!'),
  S('s125', 'The king had a big red ring.', ['the', 'king', 'had', 'a', 'big', 'red', 'ring'], 37, '🤴💍', ['🤴👑', '👸💍']),
  S('s126', 'Philip rang the gong. Bong!', ['philip', 'rang', 'the', 'gong', 'bong'], 37, '👦🔔', ['👦🥁', '👧🔔'], 'Read it, then shout BONG!'),
  S('s127', 'Dan is fishing and singing.', ['dan', 'is', 'fishing', 'and', 'singing'], 40, '👦🎣🎶', ['👦🎣📖', '👧🎣🎶']),
  S('s128', 'Is the dog digging in the mud?', ['is', 'the', 'dog', 'digging', 'in', 'the', 'mud'], 40, '🐶🕳️', ['🐱🕳️', '🐶🛁']),
  S('s129', 'Pam\'s rabbit is running up the hill.', ['pam', 'rabbit', 'is', 'running', 'up', 'the', 'hill'], 40, '🐰⛰️', ['🐢⛰️', '🐰🏠'], 'Read it fast like a running rabbit!'),
  S('s130', 'Mom is sending Dad a big bag of mints.', ['mom', 'is', 'sending', 'dad', 'a', 'big', 'bag', 'of', 'mints'], 41, '👩📦🍬', ['👨📦🍬', '👩📦🍎'], 'Read it like you\'re mailing a big surprise!'),
  S('s131', 'Sam is fishing in the pond.', ['sam', 'is', 'fishing', 'in', 'the', 'pond'], 41, '👦🎣🐟', ['👦🏊🐟', '👧🎣🐟']),
  S('s132', 'Her rabbit is munching in the basket.', ['her', 'rabbit', 'is', 'munching', 'in', 'the', 'basket'], 43, '🐰🧺', ['🐱🧺', '🐰📦'], 'Read it while nibbling like a bunny!'),
  S('s133', 'Dad left his raft at the pond for fishing in the summer.', ['dad', 'left', 'his', 'raft', 'at', 'the', 'pond', 'for', 'fishing', 'in', 'the', 'summer'], 45, '👨🛶🎣', ['👩🛶🎣', '👨🛶⛄']),
  S('s134', 'Mom\'s rabbit is soft.', ['mom', 'rabbit', 'is', 'soft'], 45, '👩🐰', ['👩🐶', '👨🐰'], 'Read it in your softest, gentlest voice.'),
  S('s135', 'That cat is a pest!', ['that', 'cat', 'is', 'a', 'pest'], 48, '🐱💥', ['🐶💥', '🐱😴'], 'Read it like a grumpy grown-up!'),
  S('s136', 'The hen had chicks in the nest.', ['the', 'hen', 'had', 'chicks', 'in', 'the', 'nest'], 48, '🐔🐤🪺', ['🐔🥚🪺', '🦆🐤🪺']),
  S('s137', 'Dad went west and is lost.', ['dad', 'went', 'west', 'and', 'is', 'lost'], 48, '👨🧭❓', ['👩🧭❓', '👨🗺️🏡'], 'Read it like you\'re calling out for Dad!'),
  S('s138', 'Dad went shopping for milk.', ['dad', 'went', 'shopping', 'for', 'milk'], 49, '👨🛒🥛', ['👩🛒🥛', '👨🛒🍞'], 'Read it in a big dad voice!'),
  S('s139', 'Pam is dusting the shelf.', ['pam', 'is', 'dusting', 'the', 'shelf'], 49, '👧🧹📚', ['👦🧹📚', '👧🧹🪟']),
  S('s140', 'Help Mom pack the quilt.', ['help', 'mom', 'pack', 'the', 'quilt'], 51, '👩🛏️🧳', ['👩🐶🧳', '👨🛏️🧳'], 'Read it like you\'re in a big hurry to pack!'),
  S('s141', 'Chance sat and did not budge.', ['chance', 'sat', 'and', 'did', 'not', 'budge'], 53, '🐕🛑', ['🐕🏃', '🐈🛑'], 'Read it in a stubborn voice!'),
  S('s142', 'Philip put the dense fudge in the box.', ['philip', 'put', 'the', 'dense', 'fudge', 'in', 'the', 'box'], 54, '👦🍫📦', ['👦🍪📦', '👧🍫📦'], 'Read it slowly, like sticky fudge!'),
  S('s143', 'Madge can pet the rabbit at once.', ['madge', 'can', 'pet', 'the', 'rabbit', 'at', 'once'], 54, '👧🖐️🐰', ['👧🖐️🐱', '👦🖐️🐰']),
  S('s144', 'Frank had a French flag on his deck.', ['frank', 'had', 'a', 'french', 'flag', 'on', 'his', 'deck'], 58, '👦🇫🇷🏡', ['👦🏴‍☠️🏡', '👧🇫🇷🏡'], 'Read it proudly, like waving a flag!'),
  S('s145', 'The dentist can help Philip floss and rinse.', ['the', 'dentist', 'can', 'help', 'philip', 'floss', 'and', 'rinse'], 58, '🧑‍⚕️😁🦷', ['🧑‍⚕️😁👂', '👮😁🦷']),
  S('s146', 'Mom put drinks and fresh sandwiches in the big picnic basket.', ['mom', 'put', 'drinks', 'and', 'fresh', 'sandwiches', 'in', 'the', 'big', 'picnic', 'basket'], 58, '🧺🥪🧃', ['🧺🍕🧃', '🎒🥪🧃'], 'Read it like you\'re excited for a picnic!'),
  S('s147', 'Fluff the rabbit can munch on the plant in the big hedge.', ['fluff', 'the', 'rabbit', 'can', 'munch', 'on', 'the', 'plant', 'in', 'the', 'big', 'hedge'], 60, '🐰🌿', ['🐰🥕', '🐶🌿'], 'Read it like a hungry bunny!'),
  S('s148', 'Scot can swim, splish, and splash in the pond.', ['scot', 'can', 'swim', 'splish', 'and', 'splash', 'in', 'the', 'pond'], 63, '🏊💦🐸', ['🏊🛁', '🚴💦🐸'], 'Read it with a big splish-splash voice!'),
  S('s149', 'Stop, Gwen! I smell a big skunk in that log.', ['stop', 'gwen', 'i', 'smell', 'a', 'big', 'skunk', 'in', 'that', 'log'], 63, '✋🦨🪵', ['✋🐶🪵', '🦨📦'], 'Hold your nose and read it again!'),
  S('s150', 'Greg and his dad ran on the track.', ['greg', 'and', 'his', 'dad', 'ran', 'on', 'the', 'track'], 65, '👦👨🏃', ['👦🏃', '👦👨🏊'], 'Read it fast like a runner zooming by!'),
  S('s151', 'I spot twelve slugs on the plant.', ['i', 'spot', 'twelve', 'slugs', 'on', 'the', 'plant'], 65, '👀🐌🌱', ['👀🐝🌱', '👀🐌🌳']),
  S('s152', 'The pup dug in the twigs.', ['the', 'pup', 'dug', 'in', 'the', 'twigs'], 65, '🐶🕳️🌿', ['🐶🦴', '🐱🕳️🌿']),
  S('s153', 'Mom made a cake.', ['mom', 'made', 'a', 'cake'], 67, '👩🎂', ['👩🍕', '👧🎂'], 'Read it like a proud baker!'),
  S('s154', 'Jane ate the cake.', ['jane', 'ate', 'the', 'cake'], 67, '👧😋🎂', ['👧😋🍎', '👦😋🎂']),
  S('s155', 'The skunks are in the log.', ['the', 'skunks', 'are', 'in', 'the', 'log'], 67, '🦨🦨🪵', ['🦨🦨📦', '🐿️🐿️🪵'], 'Read it in a whisper so the skunks stay asleep!'),
  S('s156', 'Jane did not bake the cake.', ['jane', 'did', 'not', 'bake', 'the', 'cake'], 69, '👧🚫🎂', ['👧🎂', '👧🚫🍪'], 'Shake your head when you read the word \'not\'!'),
  S('s157', 'The quick snake is in the sand.', ['the', 'quick', 'snake', 'is', 'in', 'the', 'sand'], 69, '🐍🏖️', ['🐍💧', '🦎🏖️']),
  S('s158', 'Is the rabbit safe in the shed?', ['is', 'the', 'rabbit', 'safe', 'in', 'the', 'shed'], 69, '🐰🛖✅', ['🦊🛖', '🐰🌳']),
  S('s159', 'Mom said, "Wait for Dad on the trail. Jill is lost again."', ['mom', 'said', 'wait', 'for', 'dad', 'on', 'the', 'trail', 'jill', 'is', 'lost', 'again'], 71, '👩🗣️🌲', ['👨🗣️🌲', '👩🗣️🏖️']),
  S('s160', 'Dad said, "Did Pam spot the snail in the rain?"', ['dad', 'said', 'did', 'pam', 'spot', 'the', 'snail', 'in', 'the', 'rain'], 71, '👧🐌🌧️', ['👧🐌☀️', '👧🐸🌧️'], 'Read it slooowly, like a snail sliding by!'),
  S('s161', '"Isn\'t that the quick quail?" asked Gwen.', ['isn\'t', 'that', 'the', 'quick', 'quail', 'asked', 'gwen'], 71, '👧🐦💨', ['👦🐦💨', '👧🐔💨']),
  S('s162', 'Stay away! That is the gray quail\'s eggs.', ['stay', 'away', 'that', 'is', 'the', 'gray', 'quail', 'eggs'], 73, '🐦🥚🚫', ['🐔🥚🚫', '🐦🍳🚫'], 'Read it loud, like you\'re guarding the nest!'),
  S('s163', 'Kay can play with the clay.', ['kay', 'can', 'play', 'with', 'the', 'clay'], 73, '👧🏺🙌', ['👦🏺🙌', '👧🧸🙌']),
  S('s164', 'That isn\'t a stray dog.', ['that', 'isn\'t', 'a', 'stray', 'dog'], 73, '🐶🏠✅', ['🐶❓💨', '🐱🏠✅']),
  S('s165', 'Their big sleigh can slip away!', ['their', 'big', 'sleigh', 'can', 'slip', 'away'], 75, '🛷💨❄️', ['🛷🛑❄️', '🚗💨❄️'], 'Read it fast, like a sleigh whooshing downhill!'),
  S('s166', 'His hat was beige.', ['his', 'hat', 'was', 'beige'], 75, '👦👒', ['👦🎩', '👧👒']),
  S('s167', 'Their eight quails ran away.', ['their', 'eight', 'quails', 'ran', 'away'], 75, '8️⃣🐦💨', ['3️⃣🐦💨', '8️⃣🐦🛑']),
  S('s168', 'Dad, a fawn is on the lawn!', ['dad', 'a', 'fawn', 'is', 'on', 'the', 'lawn'], 77, '🦌🌿🏡', ['🐰🌿🏡', '🦌🛣️🏡'], 'Read it in an excited whisper so you don\'t scare the fawn!'),
  S('s169', 'Can his aunt make the sauce?', ['can', 'his', 'aunt', 'make', 'the', 'sauce'], 77, '👩🍅🥣', ['👨🍅🥣', '👩🎂🥣']),
  S('s170', 'Her straw hat is lost.', ['her', 'straw', 'hat', 'is', 'lost'], 77, '👧👒❓', ['👧👒✅', '👧🧤❓']),
  S('s171', 'Mama, that cat hid the yarn!', ['mama', 'that', 'cat', 'hid', 'the', 'yarn'], 79, '🐱🧶🙈', ['🐶🧶🙈', '🐱🧦🙈'], 'Read it like you just caught that sneaky cat!'),
  S('s172', 'Is mom sick? Did mom sip a warm drink?', ['is', 'mom', 'sick', 'did', 'mom', 'sip', 'a', 'warm', 'drink'], 81, '🤒☕', ['😀☕', '🤒🍦'], 'Read it softly, like mom is resting!'),
  S('s173', 'Pam\'s aunt made a quart of the red sauce.', ['pam', 'aunt', 'made', 'a', 'quart', 'of', 'the', 'red', 'sauce'], 81, '👩🍅🥫', ['👨🍅🥫', '👩🍪']),
  S('s174', 'That swarm of bees can sting!', ['that', 'swarm', 'of', 'bees', 'can', 'sting'], 83, '🐝🐝⚡', ['🐝🌸', '🦋🦋'], 'Read it fast, like buzzing bees!'),
  S('s175', 'Can Patrick pack the cheese sandwiches in the picnic basket?', ['can', 'patrick', 'pack', 'the', 'cheese', 'sandwiches', 'in', 'the', 'picnic', 'basket'], 83, '🧀🥪🧺', ['🥪🎒', '🍎🧺']),
  S('s176', 'Her sweet rabbit can sleep in the warm basket.', ['her', 'sweet', 'rabbit', 'can', 'sleep', 'in', 'the', 'warm', 'basket'], 83, '🐇😴🧺', ['🐇🥕🧺', '🐱😴🧺'], 'Read it in a hushed voice so the bunny stays asleep!'),
  S('s177', 'She can sit in the truck.', ['she', 'can', 'sit', 'in', 'the', 'truck'], 85, '👧🚚', ['👧🚗', '🐶🚚'], 'Read it loud, like a big truck horn!'),
  S('s178', 'He can see the green eel.', ['he', 'can', 'see', 'the', 'green', 'eel'], 85, '👦🟢🐍', ['👦🟢🐸', '👧🟢🐍']),
  S('s179', 'Did we sleep on the ship?', ['did', 'we', 'sleep', 'on', 'the', 'ship'], 85, '😴🚢', ['😴🛏️', '🎉🚢'], 'Read it in a sleepy, yawny voice!'),
  S('s180', 'Steve, where is the feast?', ['steve', 'where', 'is', 'the', 'feast'], 88, '👦❓🍗', ['👦❓🍎', '👧❓🍗'], 'Read it like your tummy is rumbling!'),
  S('s181', 'Please freeze the peach cream.', ['please', 'freeze', 'the', 'peach', 'cream'], 88, '🍑🍦❄️', ['🍑🍦🔥', '🍎🍦❄️']),
  S('s182', 'Here is a real leaf on the tree.', ['here', 'is', 'a', 'real', 'leaf', 'on', 'the', 'tree'], 88, '🍃🌳', ['🌸🌳', '🍎🌳']),
  S('s183', 'The bad flea is on the cat.', ['the', 'bad', 'flea', 'is', 'on', 'the', 'cat'], 89, '🐜🐱', ['🐜🐶', '🦋🐱'], 'Read it with an itchy scritchy-scratch voice!'),
  S('s184', 'Mama can sit and sip warm tea.', ['mama', 'can', 'sit', 'and', 'sip', 'warm', 'tea'], 89, '👩🍵', ['👩🥛', '👨🍵']),
  S('s185', 'Papa, where is the peach tree?', ['papa', 'where', 'is', 'the', 'peach', 'tree'], 89, '👨❓🍑', ['👨❓🍎', '👩❓🍑']),
  S('s186', 'That is the fierce bad rabbit!', ['that', 'is', 'the', 'fierce', 'bad', 'rabbit'], 91, '🐰😠', ['🐰😊', '🐶😠'], 'Read it in a big growly voice!'),
  S('s187', 'That fiend is a cake thief!', ['that', 'fiend', 'is', 'a', 'cake', 'thief'], 91, '🦹🍰', ['🦹🍪', '👮🍰'], 'Read it like you just caught the thief!'),
  S('s188', 'Father can wield a big shield.', ['father', 'can', 'wield', 'a', 'big', 'shield'], 91, '👨🛡️', ['👨⚔️', '👦🛡️']),
  S('s189', 'A baby deer is a fawn.', ['a', 'baby', 'deer', 'is', 'a', 'fawn'], 93, '🦌🍼', ['🐰🍼', '🐶🍼']),
  S('s190', 'A baby rabbit is a bunny.', ['a', 'baby', 'rabbit', 'is', 'a', 'bunny'], 93, '🐰🍼', ['🦌🍼', '🐰🥕']),
  S('s191', 'A baby dog is a puppy.', ['a', 'baby', 'dog', 'is', 'a', 'puppy'], 93, '🐶🍼', ['🐱🍼', '🐶🦴'], 'Read it with a happy puppy yip!'),
  S('s192', 'Can she bake berry pie?', ['can', 'she', 'bake', 'berry', 'pie'], 95, '👧🫐🥧', ['👧🍎🥧', '👧🫐🧁'], 'Read it like you smell yummy pie!'),
  S('s193', 'It is a warm sunny day.', ['it', 'is', 'a', 'warm', 'sunny', 'day'], 95, '☀️😊', ['🌧️😊', '☀️🥶'], 'Read it like you\'re soaking up the sun!'),
  S('s194', 'Sorry, the truck is messy.', ['sorry', 'the', 'truck', 'is', 'messy'], 95, '🚚🗑️', ['🚗🗑️', '🚚✨']),
  S('s195', 'Where can mice hide? Mice can hide in a log.', ['where', 'can', 'mice', 'hide', 'mice', 'can', 'hide', 'in', 'a', 'log'], 97, '🐭🪵', ['🐭📦', '🐿️🪵'], 'Read it in a tiny mouse squeak!'),
  S('s196', 'We can freeze the sweet peach ice cream.', ['we', 'can', 'freeze', 'the', 'sweet', 'peach', 'ice', 'cream'], 97, '🍑🍦❄️', ['🍓🍦❄️', '🍑🍦🔥'], 'Read it with a brrr, so cold!'),
  S('s197', 'The geese nest in a pine tree by that shack.', ['the', 'geese', 'nest', 'in', 'a', 'pine', 'tree', 'by', 'that', 'shack'], 97, '🪿🌲', ['🪿🌴', '🐦🌲']),
  S('s198', 'That lamp is a bright light.', ['that', 'lamp', 'is', 'a', 'bright', 'light'], 99, '💡✨', ['🕯️✨', '💡🌑']),
  S('s199', 'Might Father light the fire?', ['might', 'father', 'light', 'the', 'fire'], 99, '👨🔥', ['👦🔥', '👨💧']),
  S('s200', 'Did the skunk and the dog fight last night?', ['did', 'the', 'skunk', 'and', 'the', 'dog', 'fight', 'last', 'night'], 99, '🦨🐶🌙', ['🦨🐱🌙', '🦨🐶☀️'], 'Read it in a spooky nighttime voice!'),
  S('s201', 'Why is the quail in the field?', ['why', 'is', 'the', 'quail', 'in', 'the', 'field'], 100, '🐦🌾', ['🐦🌊', '🦆🌾']),
  S('s202', 'Bonnie, fry the hot berry pie.', ['bonnie', 'fry', 'the', 'hot', 'berry', 'pie'], 100, '👧🍳🥧', ['👧🍳🍕', '👦🍳🥧']),
  S('s203', 'Can we feed the mice cheese?', ['can', 'we', 'feed', 'the', 'mice', 'cheese'], 100, '🐭🧀', ['🐭🍪', '🐱🧀'], 'Read it in a squeaky mouse voice!'),
  S('s204', 'Her daughter bought a golden puppy at the farm. She laughs at the sweet and funny puppy.', ['her', 'daughter', 'bought', 'a', 'golden', 'puppy', 'at', 'the', 'farm', 'she', 'laughs', 'at', 'the', 'sweet', 'and', 'funny', 'puppy'], 102, '👧🐶', ['👧🐱', '👦🐶']),
  S('s205', 'That fish was so big we thought we had caught a shark!', ['that', 'fish', 'was', 'so', 'big', 'we', 'thought', 'we', 'had', 'caught', 'a', 'shark'], 102, '🎣🦈', ['🎣🐟', '🚤🦈'], 'Read it like you just saw a HUGE shark!'),
  S('s206', 'Bonnie, we can go home and snack on an ice cream cone.', ['bonnie', 'we', 'can', 'go', 'home', 'and', 'snack', 'on', 'an', 'ice', 'cream', 'cone'], 104, '🏠🍦', ['🏫🍦', '🏠🍕']),
  S('s207', 'Rose said, "I hope the bunny is warm and safe in the hole in the field."', ['rose', 'said', 'i', 'hope', 'the', 'bunny', 'is', 'warm', 'and', 'safe', 'in', 'the', 'hole', 'in', 'the', 'field'], 104, '🐰🕳️', ['🦊🕳️', '🐰🌳'], 'Read it soft and cozy, like tucking in a bunny.'),
  S('s208', 'The campfire made thick black smoke in the pine trees.', ['the', 'campfire', 'made', 'thick', 'black', 'smoke', 'in', 'the', 'pine', 'trees'], 104, '🔥💨🌲', ['🔥💨🌴', '🌧️☁️🌲']),
  S('s209', 'Mama\'s big boat can float on the sea. The boat had a big oak oar.', ['mama', 'big', 'boat', 'can', 'float', 'on', 'the', 'sea', 'the', 'boat', 'had', 'a', 'big', 'oak', 'oar'], 106, '⛵🌊', ['🚗🌊', '⛵⛰️'], 'Read it slow and swishy, like waves on the sea.'),
  S('s210', 'Papa said, "The snow is cold. Bonnie and Rose can put on the warm coats in the sleigh."', ['papa', 'said', 'the', 'snow', 'is', 'cold', 'bonnie', 'and', 'rose', 'can', 'put', 'on', 'the', 'warm', 'coats', 'in', 'the', 'sleigh'], 106, '❄️🧥🛷', ['☀️🧥🛷', '❄️👗🛷']),
  S('s211', 'We couldn\'t look at the big moose at the zoo.', ['we', 'couldn\'t', 'look', 'at', 'the', 'big', 'moose', 'at', 'the', 'zoo'], 108, '🙈🫎', ['👀🫎', '🙈🐘']),
  S('s212', 'Look, Sam bit a cookie and lost his tooth!', ['look', 'sam', 'bit', 'a', 'cookie', 'and', 'lost', 'his', 'tooth'], 108, '🍪🦷', ['🍰🦷', '🍪😁'], 'Read it with a big gasp — oh no, a tooth!'),
  S('s213', 'He shouldn\'t tell the kids the moon is made of cheese.', ['he', 'shouldn\'t', 'tell', 'the', 'kids', 'the', 'moon', 'is', 'made', 'of', 'cheese'], 108, '🌕🧀', ['🌕🍪', '☀️🧀'], 'Read it like you are telling a silly secret!'),
  S('s214', 'I doubt that noise would annoy the brown cow.', ['i', 'doubt', 'that', 'noise', 'would', 'annoy', 'the', 'brown', 'cow'], 112, '🐄📢', ['🐖📢', '🐄🤫'], 'Read it in your best deep cow moo voice!'),
  S('s215', 'Your joyful voice is good for the stage!', ['your', 'joyful', 'voice', 'is', 'good', 'for', 'the', 'stage'], 112, '😄🎤🎭', ['😴🎤🎭', '😄🥁🎭'], 'Read it like a star taking a bow on stage!'),
  S('s216', 'Sue, is that blue fruit a berry?', ['sue', 'is', 'that', 'blue', 'fruit', 'a', 'berry'], 114, '👧🫐❓', ['👧🍎❓', '👦🫐❓']),
  S('s217', 'We had fruit juice on the cruise.', ['we', 'had', 'fruit', 'juice', 'on', 'the', 'cruise'], 114, '🧃🛳️', ['🥛🛳️', '🧃✈️']),
  S('s218', 'That huge cloud looks like a clown!', ['that', 'huge', 'cloud', 'looks', 'like', 'a', 'clown'], 114, '☁️🤡', ['☁️🐘', '🌙🤡'], 'Read it like you just spotted it in the sky!'),
];
