import type { Word } from './types';

/**
 * Word bank for game levels 1–3 (book lessons 1–30).
 * Seeded from the photographed book pages; every word is decodable at its
 * `lesson` using only graphemes/memory words taught by then (validator-enforced).
 *
 * `emoji` is the picture revealed AFTER the word is decoded — never before.
 * Abstract words (has, and, was…) have no picture and only appear in
 * mechanics that don't need one.
 */

const W = (
  text: string,
  graphemes: string[],
  lesson: number,
  emoji?: string,
  heartIndexes?: number[],
): Word => ({
  id: text.toLowerCase(),
  text,
  graphemes,
  lesson,
  ...(emoji ? { emoji } : {}),
  ...(heartIndexes ? { heartIndexes } : {}),
});

export const WORDS: Word[] = [
  // ---- Level 1 · book lessons 1–9 (a + consonants) ----
  // The article "a" appears in book sentences from lesson 3 ("A man has a hat.")
  W('a', ['a'], 3),
  W('am', ['a', 'm'], 1),
  W('an', ['a', 'n'], 1),
  W('at', ['a', 't'], 1),
  W('ax', ['a', 'x'], 1, '🪓'),
  W('ant', ['a', 'n', 't'], 1, '🐜'),
  W('Sam', ['S', 'a', 'm'], 1, '👦'),
  W('sat', ['s', 'a', 't'], 1),
  W('mat', ['m', 'a', 't'], 1),
  W('man', ['m', 'a', 'n'], 1, '👨'),
  W('ham', ['h', 'a', 'm'], 2, '🍖'),
  W('hat', ['h', 'a', 't'], 2, '👒'),
  W('has', ['h', 'a', 's'], 2),
  W('Tam', ['T', 'a', 'm'], 2, '👧'),
  W('tax', ['t', 'a', 'x'], 2),
  W('as', ['a', 's'], 3),
  W('dad', ['d', 'a', 'd'], 4, '👨'),
  W('had', ['h', 'a', 'd'], 4),
  W('sad', ['s', 'a', 'd'], 4, '😢'),
  W('mad', ['m', 'a', 'd'], 4, '😠'),
  W('and', ['a', 'n', 'd'], 4),
  W('sand', ['s', 'a', 'n', 'd'], 4, '🏖️'),
  W('hand', ['h', 'a', 'n', 'd'], 4, '✋'),
  W('wax', ['w', 'a', 'x'], 4, '🕯️'),
  W('Max', ['M', 'a', 'x'], 4, '👦'),
  W('Dan', ['D', 'a', 'n'], 4, '👦'),
  W('dam', ['d', 'a', 'm'], 4),
  W('was', ['w', 'a', 's'], 5, undefined, [1]),
  W('lad', ['l', 'a', 'd'], 6, '👦'),
  W('land', ['l', 'a', 'n', 'd'], 6, '🏝️'),
  W('last', ['l', 'a', 's', 't'], 6),
  W('cat', ['c', 'a', 't'], 7, '🐱'),
  W('can', ['c', 'a', 'n'], 7, '🥫'),
  W('bat', ['b', 'a', 't'], 7, '🦇'),
  W('bag', ['b', 'a', 'g'], 7, '👜'),
  W('fan', ['f', 'a', 'n'], 7, '🪭'),
  W('fat', ['f', 'a', 't'], 7),
  W('jam', ['j', 'a', 'm'], 7, '🫙'),
  W('gas', ['g', 'a', 's'], 7, '⛽'),
  W('fast', ['f', 'a', 's', 't'], 7, '💨'),
  W('flag', ['f', 'l', 'a', 'g'], 7, '🚩'),
  W('pan', ['p', 'a', 'n'], 8, '🍳'),
  W('rat', ['r', 'a', 't'], 8, '🐀'),
  W('ran', ['r', 'a', 'n'], 8, '🏃'),
  W('van', ['v', 'a', 'n'], 8, '🚐'),
  W('map', ['m', 'a', 'p'], 8, '🗺️'),
  W('nap', ['n', 'a', 'p'], 8, '😴'),
  W('cap', ['c', 'a', 'p'], 8, '🧢'),
  W('lap', ['l', 'a', 'p'], 8),
  W('tap', ['t', 'a', 'p'], 8, '🚰'),
  W('rag', ['r', 'a', 'g'], 8),
  W('plant', ['p', 'l', 'a', 'n', 't'], 8, '🪴'),
  W('yak', ['y', 'a', 'k'], 9, '🐂'),
  W('yam', ['y', 'a', 'm'], 9, '🍠'),
  W('zap', ['z', 'a', 'p'], 9, '⚡'),
  W('ask', ['a', 's', 'k'], 9),
  W('mask', ['m', 'a', 's', 'k'], 9, '🎭'),

  // ---- Level 2 · book lessons 10–17 (doubles, ck/qu, e i o u) ----
  W('pass', ['p', 'a', 'ss'], 10),
  W('grass', ['g', 'r', 'a', 'ss'], 10, '🌿'),
  W('jazz', ['j', 'a', 'zz'], 10, '🎷'),
  W('add', ['a', 'dd'], 10, '➕'),
  W('pack', ['p', 'a', 'ck'], 11, '🎒'),
  W('back', ['b', 'a', 'ck'], 11),
  W('sack', ['s', 'a', 'ck'], 11, '🛍️'),
  W('black', ['b', 'l', 'a', 'ck'], 11, '⬛'),
  W('snack', ['s', 'n', 'a', 'ck'], 11, '🍿'),
  W('quack', ['qu', 'a', 'ck'], 11, '🦆'),
  W('bed', ['b', 'e', 'd'], 13, '🛏️'),
  W('red', ['r', 'e', 'd'], 13, '🟥'),
  W('fed', ['f', 'e', 'd'], 13),
  W('leg', ['l', 'e', 'g'], 13, '🦵'),
  W('hen', ['h', 'e', 'n'], 13, '🐔'),
  W('ten', ['t', 'e', 'n'], 13, '🔟'),
  W('pen', ['p', 'e', 'n'], 13, '🖊️'),
  W('net', ['n', 'e', 't'], 13, '🥅'),
  W('pet', ['p', 'e', 't'], 13, '🐹'),
  W('wet', ['w', 'e', 't'], 13, '💧'),
  W('vet', ['v', 'e', 't'], 13, '🧑‍⚕️'),
  W('jet', ['j', 'e', 't'], 13, '✈️'),
  W('yes', ['y', 'e', 's'], 13),
  W('get', ['g', 'e', 't'], 13),
  W('tell', ['t', 'e', 'll'], 13, '🗣️'),
  W('bell', ['b', 'e', 'll'], 13, '🔔'),
  W('well', ['w', 'e', 'll'], 13),
  W('egg', ['e', 'gg'], 13, '🥚'),
  W('nest', ['n', 'e', 's', 't'], 13, '🪺'),
  W('tent', ['t', 'e', 'n', 't'], 13, '⛺'),
  W('sit', ['s', 'i', 't'], 13, '🪑'),
  W('six', ['s', 'i', 'x'], 13, '6️⃣'),
  W('big', ['b', 'i', 'g'], 13),
  W('dig', ['d', 'i', 'g'], 13, '⛏️'),
  W('pig', ['p', 'i', 'g'], 13, '🐷'),
  W('wig', ['w', 'i', 'g'], 13, '💇'),
  W('win', ['w', 'i', 'n'], 13, '🏆'),
  W('fin', ['f', 'i', 'n'], 13, '🦈'),
  W('pin', ['p', 'i', 'n'], 13, '📌'),
  W('lip', ['l', 'i', 'p'], 13, '👄'),
  W('zip', ['z', 'i', 'p'], 13, '🤐'),
  W('hid', ['h', 'i', 'd'], 13),
  W('his', ['h', 'i', 's'], 13),
  W('him', ['h', 'i', 'm'], 13),
  W('in', ['i', 'n'], 13),
  W('is', ['i', 's'], 13),
  W('it', ['i', 't'], 13),
  W('if', ['i', 'f'], 13),
  W('ill', ['i', 'll'], 13, '🤒'),
  W('fix', ['f', 'i', 'x'], 13, '🔧'),
  W('mix', ['m', 'i', 'x'], 13, '🥣'),
  W('did', ['d', 'i', 'd'], 13),
  W('sick', ['s', 'i', 'ck'], 13, '🤒'),
  W('pick', ['p', 'i', 'ck'], 13),
  W('kick', ['k', 'i', 'ck'], 13, '⚽'),
  W('quick', ['qu', 'i', 'ck'], 13, '💨'),
  W('quit', ['qu', 'i', 't'], 13),
  W('quill', ['qu', 'i', 'll'], 13, '🪶'),
  W('hill', ['h', 'i', 'll'], 13, '⛰️'),
  W('will', ['w', 'i', 'll'], 13),
  W('Bill', ['B', 'i', 'll'], 13, '👦'),
  W('Jill', ['J', 'i', 'll'], 13, '👧'),
  W('miss', ['m', 'i', 'ss'], 13),
  W('kiss', ['k', 'i', 'ss'], 13, '💋'),
  W('milk', ['m', 'i', 'l', 'k'], 13, '🥛'),
  W('dog', ['d', 'o', 'g'], 14, '🐶'),
  W('log', ['l', 'o', 'g'], 14, '🪵'),
  W('fog', ['f', 'o', 'g'], 14, '🌫️'),
  W('jog', ['j', 'o', 'g'], 14, '🏃'),
  W('hot', ['h', 'o', 't'], 14, '🔥'),
  W('pot', ['p', 'o', 't'], 14, '🍲'),
  W('dot', ['d', 'o', 't'], 14, '🔴'),
  W('got', ['g', 'o', 't'], 14),
  W('not', ['n', 'o', 't'], 14),
  W('on', ['o', 'n'], 14),
  W('top', ['t', 'o', 'p'], 14, '🔝'),
  W('mop', ['m', 'o', 'p'], 14, '🧹'),
  W('hop', ['h', 'o', 'p'], 14, '🐇'),
  W('pop', ['p', 'o', 'p'], 14, '🎈'),
  W('box', ['b', 'o', 'x'], 14, '📦'),
  W('fox', ['f', 'o', 'x'], 14, '🦊'),
  W('ox', ['o', 'x'], 14, '🐂'),
  W('job', ['j', 'o', 'b'], 14),
  W('mom', ['m', 'o', 'm'], 14, '👩'),
  W('doll', ['d', 'o', 'll'], 14, '🪆'),
  W('sock', ['s', 'o', 'ck'], 14, '🧦'),
  W('rock', ['r', 'o', 'ck'], 14, '🪨'),
  W('lock', ['l', 'o', 'ck'], 14, '🔒'),
  W('bug', ['b', 'u', 'g'], 14, '🐛'),
  W('dug', ['d', 'u', 'g'], 14),
  W('mud', ['m', 'u', 'd'], 14, '🟤'),
  W('sun', ['s', 'u', 'n'], 14, '☀️'),
  W('run', ['r', 'u', 'n'], 14, '🏃'),
  W('fun', ['f', 'u', 'n'], 14, '🎉'),
  W('bun', ['b', 'u', 'n'], 14, '🥯'),
  W('cup', ['c', 'u', 'p'], 14, '☕'),
  W('cut', ['c', 'u', 't'], 14, '✂️'),
  W('nut', ['n', 'u', 't'], 14, '🥜'),
  W('hut', ['h', 'u', 't'], 14, '🛖'),
  W('but', ['b', 'u', 't'], 14),
  W('bus', ['b', 'u', 's'], 14, '🚌'),
  W('gum', ['g', 'u', 'm'], 14, '🍬'),
  W('hug', ['h', 'u', 'g'], 14, '🤗'),
  W('tub', ['t', 'u', 'b'], 14, '🛁'),
  W('cub', ['c', 'u', 'b'], 14, '🐻'),
  W('up', ['u', 'p'], 14, '⬆️'),
  W('us', ['u', 's'], 14),
  W('pup', ['p', 'u', 'p'], 14, '🐕'),
  W('duck', ['d', 'u', 'ck'], 14, '🦆'),
  W('luck', ['l', 'u', 'ck'], 14, '🍀'),
  W('truck', ['t', 'r', 'u', 'ck'], 14, '🚚'),
  W('jump', ['j', 'u', 'm', 'p'], 14, '🤸'),

  // ---- Level 3 · book lessons 18–30 (ph th sh ch wh + memory words) ----
  W('Phil', ['Ph', 'i', 'l'], 18, '👦'),
  W('Philip', ['Ph', 'i', 'l', 'i', 'p'], 18, '👦'),
  W('the', ['th', 'e'], 19, undefined, [1]),
  W('that', ['th', 'a', 't'], 19),
  W('than', ['th', 'a', 'n'], 19),
  W('them', ['th', 'e', 'm'], 19),
  W('then', ['th', 'e', 'n'], 19),
  W('this', ['th', 'i', 's'], 19),
  W('bath', ['b', 'a', 'th'], 19, '🛁'),
  W('path', ['p', 'a', 'th'], 19, '🛤️'),
  W('with', ['w', 'i', 'th'], 19),
  W('math', ['m', 'a', 'th'], 19, '➕'),
  W('thin', ['th', 'i', 'n'], 19),
  W('moth', ['m', 'o', 'th'], 19, '🦋'),
  W('Seth', ['S', 'e', 'th'], 19, '👦'),
  W('son', ['s', 'o', 'n'], 20, '👦', [1]),
  W('won', ['w', 'o', 'n'], 20, '🏆', [1]),
  W('of', ['o', 'f'], 20, undefined, [0, 1]),
  W('off', ['o', 'ff'], 20),
  W('deck', ['d', 'e', 'ck'], 20),
  W('put', ['p', 'u', 't'], 24, undefined, [1]),
  W('pull', ['p', 'u', 'll'], 24, undefined, [1]),
  W('push', ['p', 'u', 'sh'], 26, '🛒', [1]),
  W('ship', ['sh', 'i', 'p'], 26, '🚢'),
  W('shop', ['sh', 'o', 'p'], 26, '🏪'),
  W('shut', ['sh', 'u', 't'], 26, '🚪'),
  W('shed', ['sh', 'e', 'd'], 26, '🛖'),
  W('shell', ['sh', 'e', 'll'], 26, '🐚'),
  W('fish', ['f', 'i', 'sh'], 26, '🐟'),
  W('dish', ['d', 'i', 'sh'], 26, '🍽️'),
  W('wish', ['w', 'i', 'sh'], 26, '🌠'),
  W('rush', ['r', 'u', 'sh'], 26, '💨'),
  W('cash', ['c', 'a', 'sh'], 26, '💵'),
  W('dash', ['d', 'a', 'sh'], 26),
  W('wash', ['w', 'a', 'sh'], 26, '🧼', [1]),
  W('chin', ['ch', 'i', 'n'], 28, '🙂'),
  W('chop', ['ch', 'o', 'p'], 28, '🪓'),
  W('chat', ['ch', 'a', 't'], 28, '💬'),
  W('chest', ['ch', 'e', 's', 't'], 28, '🧰'),
  W('chick', ['ch', 'i', 'ck'], 28, '🐤'),
  W('much', ['m', 'u', 'ch'], 28),
  W('rich', ['r', 'i', 'ch'], 28, '💰'),
  W('such', ['s', 'u', 'ch'], 28),
  W('check', ['ch', 'e', 'ck'], 28, '✅'),
  W('when', ['wh', 'e', 'n'], 30),
  W('whip', ['wh', 'i', 'p'], 30),
  W('whiz', ['wh', 'i', 'z'], 30, '💫'),
  W('which', ['wh', 'i', 'ch'], 30),
  W('what', ['wh', 'a', 't'], 30, undefined, [1]),
];

export const WORDS_BY_ID: ReadonlyMap<string, Word> = new Map(WORDS.map((w) => [w.id, w]));

export function getWord(id: string): Word {
  const w = WORDS_BY_ID.get(id);
  if (!w) throw new Error(`Unknown word id: ${id}`);
  return w;
}
