import type { Word } from './types';

/**
 * Word bank for game levels 1–3 (book lessons 1–30).
 * Seeded from the photographed book pages; every word is decodable at its
 * `lesson` using only graphemes/memory words taught by then (validator-enforced).
 *
 * `emoji` is the picture revealed AFTER the word is decoded — never before.
 * Abstract words (has, and, was…) have no picture and only appear in
 * mechanics that don't need one.
 */

const W = (
  text: string,
  graphemes: string[],
  lesson: number,
  emoji?: string,
  heartIndexes?: number[],
): Word => ({
  id: text.toLowerCase(),
  text,
  graphemes,
  lesson,
  ...(emoji ? { emoji } : {}),
  ...(heartIndexes ? { heartIndexes } : {}),
});

export const WORDS: Word[] = [
  // ---- Level 1 · book lessons 1–9 (a + consonants) ----
  // The article "a" appears in book sentences from lesson 3 ("A man has a hat.")
  W('a', ['a'], 3),
  W('am', ['a', 'm'], 1),
  W('an', ['a', 'n'], 1),
  W('at', ['a', 't'], 1),
  W('ax', ['a', 'x'], 1, '🪓'),
  W('ant', ['a', 'n', 't'], 1, '🐜'),
  W('Sam', ['S', 'a', 'm'], 1, '👦'),
  W('sat', ['s', 'a', 't'], 1),
  W('mat', ['m', 'a', 't'], 1),
  W('man', ['m', 'a', 'n'], 1, '👨'),
  W('ham', ['h', 'a', 'm'], 2, '🍖'),
  W('hat', ['h', 'a', 't'], 2, '👒'),
  W('has', ['h', 'a', 's'], 2),
  W('Tam', ['T', 'a', 'm'], 2, '👧'),
  W('tax', ['t', 'a', 'x'], 2),
  W('as', ['a', 's'], 3),
  W('dad', ['d', 'a', 'd'], 4, '👨'),
  W('had', ['h', 'a', 'd'], 4),
  W('sad', ['s', 'a', 'd'], 4, '😢'),
  W('mad', ['m', 'a', 'd'], 4, '😠'),
  W('and', ['a', 'n', 'd'], 4),
  W('sand', ['s', 'a', 'n', 'd'], 4, '🏖️'),
  W('hand', ['h', 'a', 'n', 'd'], 4, '✋'),
  W('wax', ['w', 'a', 'x'], 4, '🕯️'),
  W('Max', ['M', 'a', 'x'], 4, '👦'),
  W('Dan', ['D', 'a', 'n'], 4, '👦'),
  W('dam', ['d', 'a', 'm'], 4),
  W('was', ['w', 'a', 's'], 5, undefined, [1]),
  W('lad', ['l', 'a', 'd'], 6, '👦'),
  W('land', ['l', 'a', 'n', 'd'], 6, '🏝️'),
  W('last', ['l', 'a', 's', 't'], 6),
  W('cat', ['c', 'a', 't'], 7, '🐱'),
  W('can', ['c', 'a', 'n'], 7, '🥫'),
  W('bat', ['b', 'a', 't'], 7, '🦇'),
  W('bag', ['b', 'a', 'g'], 7, '👜'),
  W('fan', ['f', 'a', 'n'], 7, '🪭'),
  W('fat', ['f', 'a', 't'], 7),
  W('jam', ['j', 'a', 'm'], 7, '🫙'),
  W('gas', ['g', 'a', 's'], 7, '⛽'),
  W('fast', ['f', 'a', 's', 't'], 7, '💨'),
  W('flag', ['f', 'l', 'a', 'g'], 7, '🚩'),
  W('pan', ['p', 'a', 'n'], 8, '🍳'),
  W('rat', ['r', 'a', 't'], 8, '🐀'),
  W('ran', ['r', 'a', 'n'], 8, '🏃'),
  W('van', ['v', 'a', 'n'], 8, '🚐'),
  W('map', ['m', 'a', 'p'], 8, '🗺️'),
  W('nap', ['n', 'a', 'p'], 8, '😴'),
  W('cap', ['c', 'a', 'p'], 8, '🧢'),
  W('lap', ['l', 'a', 'p'], 8),
  W('tap', ['t', 'a', 'p'], 8, '🚰'),
  W('rag', ['r', 'a', 'g'], 8),
  W('plant', ['p', 'l', 'a', 'n', 't'], 8, '🪴'),
  W('yak', ['y', 'a', 'k'], 9, '🐂'),
  W('yam', ['y', 'a', 'm'], 9, '🍠'),
  W('zap', ['z', 'a', 'p'], 9, '⚡'),
  W('ask', ['a', 's', 'k'], 9),
  W('mask', ['m', 'a', 's', 'k'], 9, '🎭'),

  // ---- Level 2 · book lessons 10–17 (doubles, ck/qu, e i o u) ----
  W('pass', ['p', 'a', 'ss'], 10),
  W('grass', ['g', 'r', 'a', 'ss'], 10, '🌿'),
  W('jazz', ['j', 'a', 'zz'], 10, '🎷'),
  W('add', ['a', 'dd'], 10, '➕'),
  W('pack', ['p', 'a', 'ck'], 11, '🎒'),
  W('back', ['b', 'a', 'ck'], 11),
  W('sack', ['s', 'a', 'ck'], 11, '🛍️'),
  W('black', ['b', 'l', 'a', 'ck'], 11, '⬛'),
  W('snack', ['s', 'n', 'a', 'ck'], 11, '🍿'),
  W('quack', ['qu', 'a', 'ck'], 11, '🦆'),
  W('bed', ['b', 'e', 'd'], 13, '🛏️'),
  W('red', ['r', 'e', 'd'], 13, '🟥'),
  W('fed', ['f', 'e', 'd'], 13),
  W('leg', ['l', 'e', 'g'], 13, '🦵'),
  W('hen', ['h', 'e', 'n'], 13, '🐔'),
  W('ten', ['t', 'e', 'n'], 13, '🔟'),
  W('pen', ['p', 'e', 'n'], 13, '🖊️'),
  W('net', ['n', 'e', 't'], 13, '🥅'),
  W('pet', ['p', 'e', 't'], 13, '🐹'),
  W('wet', ['w', 'e', 't'], 13, '💧'),
  W('vet', ['v', 'e', 't'], 13, '🧑‍⚕️'),
  W('jet', ['j', 'e', 't'], 13, '✈️'),
  W('yes', ['y', 'e', 's'], 13),
  W('get', ['g', 'e', 't'], 13),
  W('tell', ['t', 'e', 'll'], 13, '🗣️'),
  W('bell', ['b', 'e', 'll'], 13, '🔔'),
  W('well', ['w', 'e', 'll'], 13),
  W('egg', ['e', 'gg'], 13, '🥚'),
  W('nest', ['n', 'e', 's', 't'], 13, '🪺'),
  W('tent', ['t', 'e', 'n', 't'], 13, '⛺'),
  W('sit', ['s', 'i', 't'], 13, '🪑'),
  W('six', ['s', 'i', 'x'], 13, '6️⃣'),
  W('big', ['b', 'i', 'g'], 13),
  W('dig', ['d', 'i', 'g'], 13, '⛏️'),
  W('pig', ['p', 'i', 'g'], 13, '🐷'),
  W('wig', ['w', 'i', 'g'], 13, '💇'),
  W('win', ['w', 'i', 'n'], 13, '🏆'),
  W('fin', ['f', 'i', 'n'], 13, '🦈'),
  W('pin', ['p', 'i', 'n'], 13, '📌'),
  W('lip', ['l', 'i', 'p'], 13, '👄'),
  W('zip', ['z', 'i', 'p'], 13, '🤐'),
  W('hid', ['h', 'i', 'd'], 13),
  W('his', ['h', 'i', 's'], 13),
  W('him', ['h', 'i', 'm'], 13),
  W('in', ['i', 'n'], 13),
  W('is', ['i', 's'], 13),
  W('it', ['i', 't'], 13),
  W('if', ['i', 'f'], 13),
  W('ill', ['i', 'll'], 13, '🤒'),
  W('fix', ['f', 'i', 'x'], 13, '🔧'),
  W('mix', ['m', 'i', 'x'], 13, '🥣'),
  W('did', ['d', 'i', 'd'], 13),
  W('sick', ['s', 'i', 'ck'], 13, '🤒'),
  W('pick', ['p', 'i', 'ck'], 13),
  W('kick', ['k', 'i', 'ck'], 13, '⚽'),
  W('quick', ['qu', 'i', 'ck'], 13, '💨'),
  W('quit', ['qu', 'i', 't'], 13),
  W('quill', ['qu', 'i', 'll'], 13, '🪶'),
  W('hill', ['h', 'i', 'll'], 13, '⛰️'),
  W('will', ['w', 'i', 'll'], 13),
  W('Bill', ['B', 'i', 'll'], 13, '👦'),
  W('Jill', ['J', 'i', 'll'], 13, '👧'),
  W('miss', ['m', 'i', 'ss'], 13),
  W('kiss', ['k', 'i', 'ss'], 13, '💋'),
  W('milk', ['m', 'i', 'l', 'k'], 13, '🥛'),
  W('dog', ['d', 'o', 'g'], 14, '🐶'),
  W('log', ['l', 'o', 'g'], 14, '🪵'),
  W('fog', ['f', 'o', 'g'], 14, '🌫️'),
  W('jog', ['j', 'o', 'g'], 14, '🏃'),
  W('hot', ['h', 'o', 't'], 14, '🔥'),
  W('pot', ['p', 'o', 't'], 14, '🍲'),
  W('dot', ['d', 'o', 't'], 14, '🔴'),
  W('got', ['g', 'o', 't'], 14),
  W('not', ['n', 'o', 't'], 14),
  W('on', ['o', 'n'], 14),
  W('top', ['t', 'o', 'p'], 14, '🔝'),
  W('mop', ['m', 'o', 'p'], 14, '🧹'),
  W('hop', ['h', 'o', 'p'], 14, '🐇'),
  W('pop', ['p', 'o', 'p'], 14, '🎈'),
  W('box', ['b', 'o', 'x'], 14, '📦'),
  W('fox', ['f', 'o', 'x'], 14, '🦊'),
  W('ox', ['o', 'x'], 14, '🐂'),
  W('job', ['j', 'o', 'b'], 14),
  W('mom', ['m', 'o', 'm'], 14, '👩'),
  W('doll', ['d', 'o', 'll'], 14, '🪆'),
  W('sock', ['s', 'o', 'ck'], 14, '🧦'),
  W('rock', ['r', 'o', 'ck'], 14, '🪨'),
  W('lock', ['l', 'o', 'ck'], 14, '🔒'),
  W('bug', ['b', 'u', 'g'], 14, '🐛'),
  W('dug', ['d', 'u', 'g'], 14),
  W('mud', ['m', 'u', 'd'], 14, '🟤'),
  W('sun', ['s', 'u', 'n'], 14, '☀️'),
  W('run', ['r', 'u', 'n'], 14, '🏃'),
  W('fun', ['f', 'u', 'n'], 14, '🎉'),
  W('bun', ['b', 'u', 'n'], 14, '🥯'),
  W('cup', ['c', 'u', 'p'], 14, '☕'),
  W('cut', ['c', 'u', 't'], 14, '✂️'),
  W('nut', ['n', 'u', 't'], 14, '🥜'),
  W('hut', ['h', 'u', 't'], 14, '🛖'),
  W('but', ['b', 'u', 't'], 14),
  W('bus', ['b', 'u', 's'], 14, '🚌'),
  W('gum', ['g', 'u', 'm'], 14, '🍬'),
  W('hug', ['h', 'u', 'g'], 14, '🤗'),
  W('tub', ['t', 'u', 'b'], 14, '🛁'),
  W('cub', ['c', 'u', 'b'], 14, '🐻'),
  W('up', ['u', 'p'], 14, '⬆️'),
  W('us', ['u', 's'], 14),
  W('pup', ['p', 'u', 'p'], 14, '🐕'),
  W('duck', ['d', 'u', 'ck'], 14, '🦆'),
  W('luck', ['l', 'u', 'ck'], 14, '🍀'),
  W('truck', ['t', 'r', 'u', 'ck'], 14, '🚚'),
  W('jump', ['j', 'u', 'm', 'p'], 14, '🤸'),

  // ---- Level 3 · book lessons 18–30 (ph th sh ch wh + memory words) ----
  W('Phil', ['Ph', 'i', 'l'], 18, '👦'),
  W('Philip', ['Ph', 'i', 'l', 'i', 'p'], 18, '👦'),
  W('the', ['th', 'e'], 19, undefined, [1]),
  W('that', ['th', 'a', 't'], 19),
  W('than', ['th', 'a', 'n'], 19),
  W('them', ['th', 'e', 'm'], 19),
  W('then', ['th', 'e', 'n'], 19),
  W('this', ['th', 'i', 's'], 19),
  W('bath', ['b', 'a', 'th'], 19, '🛁'),
  W('path', ['p', 'a', 'th'], 19, '🛤️'),
  W('with', ['w', 'i', 'th'], 19),
  W('math', ['m', 'a', 'th'], 19, '➕'),
  W('thin', ['th', 'i', 'n'], 19),
  W('moth', ['m', 'o', 'th'], 19, '🦋'),
  W('Seth', ['S', 'e', 'th'], 19, '👦'),
  W('son', ['s', 'o', 'n'], 20, '👦', [1]),
  W('won', ['w', 'o', 'n'], 20, '🏆', [1]),
  W('of', ['o', 'f'], 20, undefined, [0, 1]),
  W('off', ['o', 'ff'], 20),
  W('deck', ['d', 'e', 'ck'], 20),
  W('put', ['p', 'u', 't'], 24, undefined, [1]),
  W('pull', ['p', 'u', 'll'], 24, undefined, [1]),
  W('push', ['p', 'u', 'sh'], 26, '🛒', [1]),
  W('ship', ['sh', 'i', 'p'], 26, '🚢'),
  W('shop', ['sh', 'o', 'p'], 26, '🏪'),
  W('shut', ['sh', 'u', 't'], 26, '🚪'),
  W('shed', ['sh', 'e', 'd'], 26, '🛖'),
  W('shell', ['sh', 'e', 'll'], 26, '🐚'),
  W('fish', ['f', 'i', 'sh'], 26, '🐟'),
  W('dish', ['d', 'i', 'sh'], 26, '🍽️'),
  W('wish', ['w', 'i', 'sh'], 26, '🌠'),
  W('rush', ['r', 'u', 'sh'], 26, '💨'),
  W('cash', ['c', 'a', 'sh'], 26, '💵'),
  W('dash', ['d', 'a', 'sh'], 26),
  W('wash', ['w', 'a', 'sh'], 26, '🧼', [1]),
  W('chin', ['ch', 'i', 'n'], 28, '🙂'),
  W('chop', ['ch', 'o', 'p'], 28, '🪓'),
  W('chat', ['ch', 'a', 't'], 28, '💬'),
  W('chest', ['ch', 'e', 's', 't'], 28, '🧰'),
  W('chick', ['ch', 'i', 'ck'], 28, '🐤'),
  W('much', ['m', 'u', 'ch'], 28),
  W('rich', ['r', 'i', 'ch'], 28, '💰'),
  W('such', ['s', 'u', 'ch'], 28),
  W('check', ['ch', 'e', 'ck'], 28, '✅'),
  W('when', ['wh', 'e', 'n'], 30),
  W('whip', ['wh', 'i', 'p'], 30),
  W('whiz', ['wh', 'i', 'z'], 30, '💫'),
  W('which', ['wh', 'i', 'ch'], 30),
  W('what', ['wh', 'a', 't'], 30, undefined, [1]),

  // ---- Story support (early-lesson words added for the story pages) ----
  W('fell', ['f', 'e', 'll'], 13),
  W('let', ['l', 'e', 't'], 13),
  W('lost', ['l', 'o', 's', 't'], 14),

  // ---- Level 4 · book lessons 31–45 (ng, nd/nt, er/nk/nch, ct/ft/pt/xt) ----
  // Lessons 31–34 review; clusters of taught single letters are decodable.
  W('crab', ['c', 'r', 'a', 'b'], 31, '🦀'),
  W('frog', ['f', 'r', 'o', 'g'], 31, '🐸'),
  W('swim', ['s', 'w', 'i', 'm'], 31, '🏊'),
  W('swam', ['s', 'w', 'a', 'm'], 31),
  W('drum', ['d', 'r', 'u', 'm'], 31, '🥁'),
  W('glad', ['g', 'l', 'a', 'd'], 31, '😊'),
  W('clap', ['c', 'l', 'a', 'p'], 31, '👏'),
  W('grin', ['g', 'r', 'i', 'n'], 31, '😁'),
  W('trip', ['t', 'r', 'i', 'p'], 31),
  W('brush', ['b', 'r', 'u', 'sh'], 31, '🪥'),
  W('splash', ['s', 'p', 'l', 'a', 'sh'], 31, '💦'),
  W('stop', ['s', 't', 'o', 'p'], 31, '🛑'),
  W('step', ['s', 't', 'e', 'p'], 31),
  W('sled', ['s', 'l', 'e', 'd'], 31, '🛷'),
  W('all', ['a', 'll'], 35, undefined, [0]),
  W('ring', ['r', 'i', 'ng'], 37, '💍'),
  W('king', ['k', 'i', 'ng'], 37, '🤴'),
  W('sing', ['s', 'i', 'ng'], 37, '🎤'),
  W('sang', ['s', 'a', 'ng'], 37),
  W('song', ['s', 'o', 'ng'], 37, '🎵'),
  W('long', ['l', 'o', 'ng'], 37),
  W('wing', ['w', 'i', 'ng'], 37, '🪽'),
  W('wand', ['w', 'a', 'nd'], 41, '🪄', [1]),
  W('want', ['w', 'a', 'nt'], 41, undefined, [1]),
  W('pond', ['p', 'o', 'nd'], 41),
  W('wind', ['w', 'i', 'nd'], 41, '💨'),
  W('end', ['e', 'nd'], 41),
  W('send', ['s', 'e', 'nd'], 41, '💌'),
  W('went', ['w', 'e', 'nt'], 41),
  W('mint', ['m', 'i', 'nt'], 41, '🍬'),
  W('pants', ['p', 'a', 'nt', 's'], 41, '👖'),
  W('her', ['h', 'er'], 43),
  W('sister', ['s', 'i', 's', 't', 'er'], 43, '👧'),
  W('winter', ['w', 'i', 'nt', 'er'], 43, '❄️'),
  W('summer', ['s', 'u', 'm', 'm', 'er'], 43, '☀️'),
  W('pink', ['p', 'i', 'nk'], 43, '🩷'),
  W('wink', ['w', 'i', 'nk'], 43, '😉'),
  W('drink', ['d', 'r', 'i', 'nk'], 43, '🥤'),
  W('thank', ['th', 'a', 'nk'], 43),
  W('lunch', ['l', 'u', 'nch'], 43, '🥪'),
  W('branch', ['b', 'r', 'a', 'nch'], 43),
  W('fern', ['f', 'er', 'n'], 43, '🌿'),
  W('gift', ['g', 'i', 'ft'], 45, '🎁'),
  W('soft', ['s', 'o', 'ft'], 45),
  W('left', ['l', 'e', 'ft'], 45, '⬅️'),
  W('lift', ['l', 'i', 'ft'], 45, '🏋️'),
  W('raft', ['r', 'a', 'ft'], 45, '🛶'),
  W('next', ['n', 'e', 'xt'], 45),
  W('fact', ['f', 'a', 'ct'], 45),

  // ---- Level 5 · book lessons 46–65 (final clusters, tch, dge/nce, blends) ----
  W('slip', ['sl', 'i', 'p'], 61),
  W('spell', ['sp', 'e', 'll'], 47, '✨'),
  W('spill', ['sp', 'i', 'll'], 47),
  W('stem', ['st', 'e', 'm'], 47, '🌱'),
  W('still', ['st', 'i', 'll'], 47),
  W('elk', ['e', 'lk'], 49, '🦌'),
  W('held', ['h', 'e', 'ld'], 49),
  W('elf', ['e', 'lf'], 49, '🧝'),
  W('shelf', ['sh', 'e', 'lf'], 49),
  W('golf', ['g', 'o', 'lf'], 49, '⛳'),
  W('calf', ['c', 'a', 'lf'], 49, '🐄', [1, 2]),
  W('half', ['h', 'a', 'lf'], 49, undefined, [1, 2]),
  W('talk', ['t', 'a', 'lk'], 49, '🗣️', [1, 2]),
  W('walk', ['w', 'a', 'lk'], 49, '🚶', [1, 2]),
  W('help', ['h', 'e', 'lp'], 51),
  W('melt', ['m', 'e', 'lt'], 51, '🫠'),
  W('belt', ['b', 'e', 'lt'], 51),
  W('lamp', ['l', 'a', 'mp'], 51, '🪔'),
  W('camp', ['c', 'a', 'mp'], 51, '🏕️'),
  W('stamp', ['st', 'a', 'mp'], 51, '📮'),
  W('catch', ['c', 'a', 'tch'], 51, '⚾'),
  W('patch', ['p', 'a', 'tch'], 51, '🩹'),
  W('fetch', ['f', 'e', 'tch'], 51, '🎾'),
  W('halt', ['h', 'a', 'lt'], 51, '✋', [1]),
  W('bridge', ['b', 'r', 'i', 'dge'], 53, '🌉'),
  W('badge', ['b', 'a', 'dge'], 53, '🎖️'),
  W('hedge', ['h', 'e', 'dge'], 53, '🌳'),
  W('fudge', ['f', 'u', 'dge'], 53, '🍫'),
  W('prince', ['p', 'r', 'i', 'nce'], 53, '🤴'),
  W('dance', ['d', 'a', 'nce'], 53, '💃'),
  W('one', ['o', 'n', 'e'], 53, '1️⃣', [0, 2]),
  W('once', ['o', 'nce'], 53, undefined, [0]),
  W('block', ['bl', 'o', 'ck'], 55),
  W('brick', ['br', 'i', 'ck'], 55, '🧱'),
  W('club', ['cl', 'u', 'b'], 55),
  W('clock', ['cl', 'o', 'ck'], 55, '🕐'),
  W('crunch', ['cr', 'u', 'nch'], 55),
  W('dress', ['dr', 'e', 'ss'], 57, '👗'),
  W('fresh', ['fr', 'e', 'sh'], 57),
  W('flash', ['fl', 'a', 'sh'], 57, '⚡'),
  W('frost', ['fr', 'o', 'st'], 57, '❄️'),
  W('glass', ['gl', 'a', 'ss'], 59),
  W('grand', ['gr', 'a', 'nd'], 59),
  W('print', ['pr', 'i', 'nt'], 59, '🖨️'),
  W('smell', ['sm', 'e', 'll'], 61, '👃'),
  W('snap', ['sn', 'a', 'p'], 61, '🫰'),
  W('spring', ['spr', 'i', 'ng'], 61, '🌸'),
  W('shrimp', ['shr', 'i', 'mp'], 61, '🦐'),
  W('string', ['str', 'i', 'ng'], 62, '🧵'),
  W('strong', ['str', 'o', 'ng'], 62, '💪'),
  W('skunk', ['sk', 'u', 'nk'], 62, '🦨'),
  W('skip', ['sk', 'i', 'p'], 62),
  W('scrub', ['scr', 'u', 'b'], 62, '🧽'),
  W('twin', ['tw', 'i', 'n'], 64, '👯'),
  W('twist', ['tw', 'i', 'st'], 64, '🌀'),
  W('thrill', ['thr', 'i', 'll'], 64, '🎢'),
  W('trunk', ['tr', 'u', 'nk'], 64, '🐘'),

  // ---- Level 6 · book lessons 66–77 (a_e, ai, ay, eigh, au/aw) ----
  W('cake', ['c', 'a_e', 'k'], 66, '🎂'),
  W('lake', ['l', 'a_e', 'k'], 66, '🏞️'),
  W('name', ['n', 'a_e', 'm'], 66),
  W('game', ['g', 'a_e', 'm'], 66, '🎲'),
  W('wave', ['w', 'a_e', 'v'], 66, '🌊'),
  W('snake', ['s', 'n', 'a_e', 'k'], 66, '🐍'),
  W('whale', ['wh', 'a_e', 'l'], 66, '🐋'),
  W('grape', ['g', 'r', 'a_e', 'p'], 66, '🍇'),
  W('brave', ['b', 'r', 'a_e', 'v'], 66),
  W('late', ['l', 'a_e', 't'], 66),
  W('bake', ['b', 'a_e', 'k'], 66, '🧁'),
  W('plate', ['p', 'l', 'a_e', 't'], 66, '🍽️'),
  W('gate', ['g', 'a_e', 't'], 66),
  W('ate', ['a_e', 't'], 66),
  W('made', ['m', 'a_e', 'd'], 66),
  W('are', ['a', 'r', 'e'], 66, undefined, [0, 2]),
  W('have', ['h', 'a', 'v', 'e'], 66, undefined, [3]),
  W('rain', ['r', 'ai', 'n'], 70, '🌧️'),
  W('sail', ['s', 'ai', 'l'], 70, '⛵'),
  W('snail', ['sn', 'ai', 'l'], 70, '🐌'),
  W('paint', ['p', 'ai', 'nt'], 70, '🎨'),
  W('wait', ['w', 'ai', 't'], 70),
  W('train', ['tr', 'ai', 'n'], 70, '🚂'),
  W('said', ['s', 'ai', 'd'], 70, undefined, [1]),
  W('again', ['a', 'g', 'ai', 'n'], 70, undefined, [0, 2]),
  W('against', ['a', 'g', 'ai', 'n', 'st'], 70, undefined, [0, 2]),
  W('day', ['d', 'ay'], 72),
  W('play', ['pl', 'ay'], 72, '🛝'),
  W('say', ['s', 'ay'], 72),
  W('stay', ['st', 'ay'], 72),
  W('away', ['a', 'w', 'ay'], 72, undefined, [0]),
  W('eight', ['eigh', 't'], 74, '8️⃣'),
  W('neigh', ['n', 'eigh'], 74, '🐴'),
  W('height', ['h', 'eigh', 't'], 74, '📏', [1]),
  W('paw', ['p', 'aw'], 76, '🐾'),
  W('saw', ['s', 'aw'], 76, '🪚'),
  W('draw', ['dr', 'aw'], 76, '🖍️'),
  W('yawn', ['y', 'aw', 'n'], 76, '🥱'),
  W('dawn', ['d', 'aw', 'n'], 76, '🌅'),
  W('hawk', ['h', 'aw', 'k'], 76, '🦅'),
  W('launch', ['l', 'au', 'nch'], 76, '🚀'),

  // ---- Level 7 · book lessons 78–95 (ar, ee, ea, e_e, ie, y-as-vowel, uy) ----
  W('star', ['st', 'ar'], 78, '⭐'),
  W('car', ['c', 'ar'], 78, '🚗'),
  W('far', ['f', 'ar'], 78),
  W('farm', ['f', 'ar', 'm'], 78, '🚜'),
  W('shark', ['sh', 'ar', 'k'], 78, '🦈'),
  W('dark', ['d', 'ar', 'k'], 78, '🌑'),
  W('park', ['p', 'ar', 'k'], 78, '🌳'),
  W('card', ['c', 'ar', 'd'], 78, '🃏'),
  W('see', ['s', 'ee'], 82, '👀'),
  W('bee', ['b', 'ee'], 82, '🐝'),
  W('tree', ['tr', 'ee'], 82, '🌳'),
  W('feet', ['f', 'ee', 't'], 82, '🦶'),
  W('green', ['gr', 'ee', 'n'], 82, '🟩'),
  W('sleep', ['sl', 'ee', 'p'], 82, '😴'),
  W('sheep', ['sh', 'ee', 'p'], 82, '🐑'),
  W('queen', ['qu', 'ee', 'n'], 82, '👸'),
  W('sweet', ['sw', 'ee', 't'], 82, '🍭'),
  W('three', ['thr', 'ee'], 82, '3️⃣'),
  W('been', ['b', 'ee', 'n'], 84, undefined, [1]),
  W('she', ['sh', 'e'], 84, undefined, [1]),
  W('he', ['h', 'e'], 84, undefined, [1]),
  W('be', ['b', 'e'], 84, undefined, [1]),
  W('we', ['w', 'e'], 84, undefined, [1]),
  W('me', ['m', 'e'], 84, undefined, [1]),
  W('sea', ['s', 'ea'], 86, '🌊'),
  W('eat', ['ea', 't'], 86, '😋'),
  W('read', ['r', 'ea', 'd'], 86, '📖'),
  W('beach', ['b', 'ea', 'ch'], 86, '🏖️'),
  W('leaf', ['l', 'ea', 'f'], 86, '🍃'),
  W('peach', ['p', 'ea', 'ch'], 86, '🍑'),
  W('dream', ['dr', 'ea', 'm'], 86, '💭'),
  W('clean', ['cl', 'ea', 'n'], 86, '🧼'),
  W('Pete', ['P', 'e_e', 't'], 87, '👦'),
  W('these', ['th', 'e_e', 's'], 87),
  W('pie', ['p', 'ie'], 90, '🥧'),
  W('tie', ['t', 'ie'], 90, '👔'),
  W('cried', ['cr', 'ie', 'd'], 90, '😢'),
  W('tried', ['tr', 'ie', 'd'], 90),
  // Lesson 92 is y-as-vowel; 'y' the grapheme is taught, the sound is new.
  W('my', ['m', 'y'], 92),
  W('fly', ['fl', 'y'], 92, '🪰'),
  W('sky', ['sk', 'y'], 92, '🌌'),
  W('try', ['tr', 'y'], 92),
  W('happy', ['h', 'a', 'p', 'p', 'y'], 92, '😄'),
  W('funny', ['f', 'u', 'n', 'n', 'y'], 92, '😂'),
  W('buy', ['b', 'uy'], 94, '🛍️'),

  // ---- Level 8 · book lessons 96–115 (i_e, igh, o_e, oa/ow, oo, ou, oy/oi, ue/ui/u_e, ew) ----
  W('smile', ['sm', 'i_e', 'l'], 96, '😊'),
  W('bike', ['b', 'i_e', 'k'], 96, '🚲'),
  W('kite', ['k', 'i_e', 't'], 96, '🪁'),
  W('time', ['t', 'i_e', 'm'], 96, '⏰'),
  W('five', ['f', 'i_e', 'v'], 96, '5️⃣'),
  W('ride', ['r', 'i_e', 'd'], 96, '🐎'),
  W('shine', ['sh', 'i_e', 'n'], 96, '🌟'),
  W('night', ['n', 'igh', 't'], 98, '🌙'),
  W('light', ['l', 'igh', 't'], 98, '💡'),
  W('high', ['h', 'igh'], 98),
  W('bright', ['br', 'igh', 't'], 98, '✨'),
  W('laugh', ['l', 'augh'], 101, '🤣'),
  W('caught', ['c', 'augh', 't'], 101),
  W('home', ['h', 'o_e', 'm'], 103, '🏠'),
  W('bone', ['b', 'o_e', 'n'], 103, '🦴'),
  W('nose', ['n', 'o_e', 's'], 103, '👃'),
  W('rose', ['r', 'o_e', 's'], 103, '🌹'),
  W('rope', ['r', 'o_e', 'p'], 103, '🪢'),
  W('hope', ['h', 'o_e', 'p'], 103),
  W('boat', ['b', 'oa', 't'], 105, '🛥️'),
  W('goat', ['g', 'oa', 't'], 105, '🐐'),
  W('snow', ['sn', 'ow'], 105, '☃️'),
  W('slow', ['sl', 'ow'], 105, '🐢'),
  W('yellow', ['y', 'e', 'll', 'ow'], 105, '🟨'),
  W('rainbow', ['r', 'ai', 'n', 'b', 'ow'], 105, '🌈'),
  W('moon', ['m', 'oo', 'n'], 107, '🌕'),
  W('book', ['b', 'oo', 'k'], 107, '📚'),
  W('spoon', ['sp', 'oo', 'n'], 107, '🥄'),
  W('look', ['l', 'oo', 'k'], 107, '👀'),
  W('zoo', ['z', 'oo'], 107, '🦓'),
  W('out', ['ou', 't'], 109),
  W('cloud', ['cl', 'ou', 'd'], 109, '☁️'),
  W('shout', ['sh', 'ou', 't'], 109, '📣'),
  W('found', ['f', 'ou', 'nd'], 109),
  W('loud', ['l', 'ou', 'd'], 109, '🔊'),
  W('cow', ['c', 'ow'], 109, '🐄'),
  W('doubt', ['d', 'ou', 'bt'], 110, undefined, [2]),
  W('boy', ['b', 'oy'], 111, '👦'),
  W('toy', ['t', 'oy'], 111, '🧸'),
  W('coin', ['c', 'oi', 'n'], 111, '🪙'),
  W('blue', ['bl', 'ue'], 113, '🟦'),
  W('fruit', ['fr', 'ui', 't'], 113, '🍉'),
  W('cute', ['c', 'u_e', 't'], 113, '🥰'),
  W('mule', ['m', 'u_e', 'l'], 113, '🫏'),
  W('new', ['n', 'ew'], 115),
  W('flew', ['fl', 'ew'], 115),
  W('grew', ['gr', 'ew'], 115),
  W('through', ['thr', 'ough'], 115, undefined, [1]),
  W('sew', ['s', 'ew'], 115, '🪡', [1]),

  // ---- Level 9 · book lessons 116–120 (r-vowels, le/tle, ci/ti/si, silent letters) ----
  W('bird', ['b', 'ir', 'd'], 116, '🐦'),
  W('girl', ['g', 'ir', 'l'], 116, '👧'),
  W('corn', ['c', 'or', 'n'], 116, '🌽'),
  W('fork', ['f', 'or', 'k'], 116, '🍴'),
  W('turn', ['t', 'ur', 'n'], 116),
  W('earth', ['ear', 'th'], 116, '🌍'),
  W('little', ['l', 'i', 't', 'tle'], 117),
  W('apple', ['a', 'p', 'p', 'le'], 117, '🍎'),
  W('purple', ['p', 'ur', 'p', 'le'], 117, '🟪'),
  W('turtle', ['t', 'ur', 'tle'], 117, '🐢'),
  W('candle', ['c', 'a', 'nd', 'le'], 117, '🕯️'),
  W('special', ['sp', 'e', 'ci', 'a', 'l'], 118),
  W('lamb', ['l', 'a', 'mb'], 119, '🐑'),
  W('write', ['wr', 'i_e', 't'], 119, '✍️'),
  W('knight', ['kn', 'igh', 't'], 119, '🛡️'),

  // ---- The Reading Road: transcribed from the book's pages (lessons 21-120) ----
  // lesson 21
  W('Bob', ['B', 'o', 'b'], 21),
  // lesson 22
  W('cats', ['c', 'a', 't', 's'], 22, '🐱'),
  W('dogs', ['d', 'o', 'g', 's'], 22, '🐶'),
  W('pets', ['p', 'e', 't', 's'], 22, '🐾'),
  W('pots', ['p', 'o', 't', 's'], 22),
  W('pans', ['p', 'a', 'n', 's'], 22, '🍳'),
  W('boxes', ['b', 'o', 'x', 'es'], 22, '📦'),
  W('foxes', ['f', 'o', 'x', 'es'], 22, '🦊'),
  // lesson 23
  W('eggs', ['e', 'gg', 's'], 23, '🥚'),
  W('Pam', ['P', 'a', 'm'], 23),
  // lesson 24
  W('sub', ['s', 'u', 'b'], 24),
  W('bud', ['b', 'u', 'd'], 24),
  W('jug', ['j', 'u', 'g'], 24),
  W('mug', ['m', 'u', 'g'], 24, '☕'),
  W('rug', ['r', 'u', 'g'], 24),
  W('buzz', ['b', 'u', 'zz'], 24),
  W('hum', ['h', 'u', 'm'], 24),
  W('full', ['f', 'u', 'll'], 24, undefined, [1]),
  W('Jack', ['J', 'a', 'ck'], 24),
  // lesson 25
  W('bad', ['b', 'a', 'd'], 25),
  W('bib', ['b', 'i', 'b'], 25),
  W('rub', ['r', 'u', 'b'], 25),
  W('tug', ['t', 'u', 'g'], 25),
  W('sum', ['s', 'u', 'm'], 25),
  W('dull', ['d', 'u', 'll'], 25),
  W('gull', ['g', 'u', 'll'], 25),
  W('fuzz', ['f', 'u', 'zz'], 25),
  W('fuss', ['f', 'u', 'ss'], 25),
  W('mutt', ['m', 'u', 't', 't'], 25, '🐕'),
  // lesson 26
  W('ash', ['a', 'sh'], 26),
  W('shack', ['sh', 'a', 'ck'], 26, '🛖'),
  W('shin', ['sh', 'i', 'n'], 26, '🦵'),
  W('shock', ['sh', 'o', 'ck'], 26),
  W('dashes', ['d', 'a', 'sh', 'es'], 26),
  W('shells', ['sh', 'e', 'll', 's'], 26, '🐚'),
  W('Josh', ['J', 'o', 'sh'], 26),
  // lesson 27
  W('hush', ['h', 'u', 'sh'], 27, '🤫'),
  W('mash', ['m', 'a', 'sh'], 27),
  W('rash', ['r', 'a', 'sh'], 27),
  W('sash', ['s', 'a', 'sh'], 27),
  W('shall', ['sh', 'a', 'll'], 27),
  W('Jan', ['J', 'a', 'n'], 27),
  // lesson 28
  W('chess', ['ch', 'e', 'ss'], 28, '♟️'),
  W('chill', ['ch', 'i', 'll'], 28, '🥶'),
  W('chip', ['ch', 'i', 'p'], 28),
  W('chug', ['ch', 'u', 'g'], 28),
  W('chicks', ['ch', 'i', 'ck', 's'], 28, '🐤'),
  // lesson 30
  W('whack', ['wh', 'a', 'ck'], 30),
  W('whiff', ['wh', 'i', 'ff'], 30),
  // lesson 32
  W('isn\'t', ['i', 's', 'n\'t'], 32, undefined, [2]),
  W('can\'t', ['c', 'a', 'n\'t'], 32, undefined, [2]),
  W('hasn\'t', ['h', 'a', 's', 'n\'t'], 32, undefined, [3]),
  W('it\'s', ['i', 't', '\'s'], 32, undefined, [2]),
  W('let\'s', ['l', 'e', 't', '\'s'], 32, undefined, [3]),
  W('didn\'t', ['d', 'i', 'd', 'n\'t'], 32, undefined, [3]),
  // lesson 33
  W('jacket', ['j', 'a', 'ck', 'e', 't'], 33, '🧥'),
  W('tunnel', ['t', 'u', 'n', 'n', 'e', 'l'], 33),
  W('lemon', ['l', 'e', 'm', 'o', 'n'], 33, '🍋'),
  W('ticket', ['t', 'i', 'ck', 'e', 't'], 33, '🎫'),
  W('napkin', ['n', 'a', 'p', 'k', 'i', 'n'], 33),
  W('picnic', ['p', 'i', 'c', 'n', 'i', 'c'], 33),
  W('basket', ['b', 'a', 's', 'k', 'e', 't'], 33, '🧺'),
  W('goblin', ['g', 'o', 'b', 'l', 'i', 'n'], 33),
  W('rocket', ['r', 'o', 'ck', 'e', 't'], 33, '🚀'),
  W('cactus', ['c', 'a', 'c', 't', 'u', 's'], 33, '🌵'),
  W('ribbon', ['r', 'i', 'b', 'b', 'o', 'n'], 33, '🎀'),
  W('wagon', ['w', 'a', 'g', 'o', 'n'], 33),
  W('sunset', ['s', 'u', 'n', 's', 'e', 't'], 33, '🌇'),
  W('zigzag', ['z', 'i', 'g', 'z', 'a', 'g'], 33),
  // lesson 34
  W('camel', ['c', 'a', 'm', 'e', 'l'], 34, '🐫'),
  W('for', ['f', 'o', 'r'], 34),
  W('visit', ['v', 'i', 's', 'i', 't'], 34),
  W('sudden', ['s', 'u', 'dd', 'e', 'n'], 34),
  W('vivid', ['v', 'i', 'v', 'i', 'd'], 34),
  // lesson 35
  W('ball', ['b', 'a', 'll'], 35, '⚽'),
  W('call', ['c', 'a', 'll'], 35, '📞'),
  W('fall', ['f', 'a', 'll'], 35, '🍂'),
  W('mall', ['m', 'a', 'll'], 35),
  W('hall', ['h', 'a', 'll'], 35),
  W('tall', ['t', 'a', 'll'], 35),
  W('wall', ['w', 'a', 'll'], 35, '🧱'),
  W('Patrick', ['P', 'a', 't', 'r', 'i', 'ck'], 35),
  W('rabbit', ['r', 'a', 'b', 'b', 'i', 't'], 35, '🐰'),
  W('rabbits', ['r', 'a', 'b', 'b', 'i', 't', 's'], 35, '🐇'),
  // lesson 36
  W('padlock', ['p', 'a', 'd', 'l', 'o', 'ck'], 36, '🔒'),
  W('helmet', ['h', 'e', 'l', 'm', 'e', 't'], 36, '⛑️'),
  W('tablet', ['t', 'a', 'b', 'l', 'e', 't'], 36),
  W('panel', ['p', 'a', 'n', 'e', 'l'], 36),
  W('fill', ['f', 'i', 'll'], 36),
  W('pill', ['p', 'i', 'll'], 36, '💊'),
  // lesson 37
  W('bang', ['b', 'a', 'ng'], 37, '💥'),
  W('hang', ['h', 'a', 'ng'], 37),
  W('rang', ['r', 'a', 'ng'], 37),
  W('gang', ['g', 'a', 'ng'], 37),
  W('ding', ['d', 'i', 'ng'], 37),
  W('gong', ['g', 'o', 'ng'], 37),
  W('bong', ['b', 'o', 'ng'], 37),
  W('hung', ['h', 'u', 'ng'], 37),
  W('lung', ['l', 'u', 'ng'], 37, '🫁'),
  W('rung', ['r', 'u', 'ng'], 37),
  W('sung', ['s', 'u', 'ng'], 37),
  // lesson 39
  W('kid', ['k', 'i', 'd'], 39, '🧒'),
  W('yell', ['y', 'e', 'll'], 39),
  W('toss', ['t', 'o', 'ss'], 39),
  W('running', ['r', 'u', 'n', 'n', 'i', 'ng'], 39, '🏃'),
  W('ringing', ['r', 'i', 'ng', 'i', 'ng'], 39),
  W('napping', ['n', 'a', 'p', 'p', 'i', 'ng'], 39, '😴'),
  W('shopping', ['sh', 'o', 'p', 'p', 'i', 'ng'], 39, '🛍️'),
  W('digging', ['d', 'i', 'gg', 'i', 'ng'], 39),
  W('wishing', ['w', 'i', 'sh', 'i', 'ng'], 39),
  W('yelling', ['y', 'e', 'll', 'i', 'ng'], 39),
  W('tossing', ['t', 'o', 'ss', 'i', 'ng'], 39),
  W('fixing', ['f', 'i', 'x', 'i', 'ng'], 39, '🔧'),
  W('mixing', ['m', 'i', 'x', 'i', 'ng'], 39),
  W('locking', ['l', 'o', 'ck', 'i', 'ng'], 39),
  // lesson 40
  W('fishing', ['f', 'i', 'sh', 'i', 'ng'], 40, '🎣'),
  W('singing', ['s', 'i', 'ng', 'i', 'ng'], 40, '🎤'),
  // lesson 41
  W('hint', ['h', 'i', 'nt'], 41),
  W('rent', ['r', 'e', 'nt'], 41),
  W('sending', ['s', 'e', 'nd', 'i', 'ng'], 41),
  W('mints', ['m', 'i', 'nt', 's'], 41),
  // lesson 42
  W('bend', ['b', 'e', 'nd'], 42),
  W('bending', ['b', 'e', 'nd', 'i', 'ng'], 42),
  W('mend', ['m', 'e', 'nd'], 42),
  W('mending', ['m', 'e', 'nd', 'i', 'ng'], 42),
  W('hunt', ['h', 'u', 'nt'], 42),
  W('hunting', ['h', 'u', 'nt', 'i', 'ng'], 42),
  W('landing', ['l', 'a', 'nd', 'i', 'ng'], 42),
  W('vent', ['v', 'e', 'nt'], 42),
  W('zigzagging', ['z', 'i', 'g', 'z', 'a', 'gg', 'i', 'ng'], 42),
  W('galloping', ['g', 'a', 'll', 'o', 'p', 'i', 'ng'], 42, '🐎'),
  W('rocketing', ['r', 'o', 'ck', 'e', 't', 'i', 'ng'], 42, '🚀'),
  // lesson 43
  W('letter', ['l', 'e', 't', 't', 'er'], 43, '✉️'),
  W('better', ['b', 'e', 't', 't', 'er'], 43),
  W('butter', ['b', 'u', 't', 't', 'er'], 43, '🧈'),
  W('bank', ['b', 'a', 'nk'], 43, '🏦'),
  W('tank', ['t', 'a', 'nk'], 43),
  W('ink', ['i', 'nk'], 43),
  W('sink', ['s', 'i', 'nk'], 43),
  W('junk', ['j', 'u', 'nk'], 43),
  W('bunch', ['b', 'u', 'nch'], 43),
  W('bench', ['b', 'e', 'nch'], 43),
  W('punch', ['p', 'u', 'nch'], 43, '👊'),
  W('munching', ['m', 'u', 'nch', 'i', 'ng'], 43),
  // lesson 44
  W('honk', ['h', 'o', 'nk'], 44),
  W('ranch', ['r', 'a', 'nch'], 44),
  W('finch', ['f', 'i', 'nch'], 44, '🐦'),
  W('sinking', ['s', 'i', 'nk', 'i', 'ng'], 44),
  W('chatter', ['ch', 'a', 't', 't', 'er'], 44),
  W('munch', ['m', 'u', 'nch'], 44),
  W('pinch', ['p', 'i', 'nch'], 44),
  W('hunter', ['h', 'u', 'nt', 'er'], 44),
  // lesson 45
  W('act', ['a', 'ct'], 45),
  W('kept', ['k', 'e', 'pt'], 45),
  W('text', ['t', 'e', 'xt'], 45),
  W('wept', ['w', 'e', 'pt'], 45, '😭'),
  W('loft', ['l', 'o', 'ft'], 45),
  W('sift', ['s', 'i', 'ft'], 45),
  // lesson 46
  W('acting', ['a', 'ct', 'i', 'ng'], 46, '🎭'),
  W('rafting', ['r', 'a', 'ft', 'i', 'ng'], 46),
  W('texting', ['t', 'e', 'xt', 'i', 'ng'], 46, '📱'),
  W('lifting', ['l', 'i', 'ft', 'i', 'ng'], 46, '🏋️'),
  W('sifting', ['s', 'i', 'ft', 'i', 'ng'], 46),
  // lesson 47
  W('desk', ['d', 'e', 'sk'], 47),
  W('best', ['b', 'e', 'st'], 47),
  W('rest', ['r', 'e', 'st'], 47),
  W('list', ['l', 'i', 'st'], 47, '📝'),
  W('must', ['m', 'u', 'st'], 47),
  W('past', ['p', 'a', 'st'], 47),
  W('cast', ['c', 'a', 'st'], 47),
  W('dusk', ['d', 'u', 'sk'], 47, '🌆'),
  W('gasp', ['g', 'a', 'sp'], 47, '😮'),
  W('mist', ['m', 'i', 'st'], 47, '🌫️'),
  W('rust', ['r', 'u', 'st'], 47),
  W('disk', ['d', 'i', 'sk'], 47, '💿'),
  // lesson 48
  W('pest', ['p', 'e', 'st'], 48),
  W('west', ['w', 'e', 'st'], 48),
  // lesson 49
  W('bulb', ['b', 'u', 'lb'], 49, '💡'),
  W('silk', ['s', 'i', 'lk'], 49),
  W('sulk', ['s', 'u', 'lk'], 49),
  W('self', ['s', 'e', 'lf'], 49),
  W('weld', ['w', 'e', 'ld'], 49),
  W('dusting', ['d', 'u', 'st', 'i', 'ng'], 49),
  // lesson 50
  W('golfing', ['g', 'o', 'lf', 'i', 'ng'], 50, '⛳'),
  W('milking', ['m', 'i', 'lk', 'i', 'ng'], 50),
  W('welding', ['w', 'e', 'ld', 'i', 'ng'], 50),
  W('sulking', ['s', 'u', 'lk', 'i', 'ng'], 50),
  // lesson 51
  W('elm', ['e', 'lm'], 51, '🌳'),
  W('film', ['f', 'i', 'lm'], 51, '🎬'),
  W('yelp', ['y', 'e', 'lp'], 51),
  W('gulp', ['g', 'u', 'lp'], 51),
  W('felt', ['f', 'e', 'lt'], 51),
  W('quilt', ['qu', 'i', 'lt'], 51),
  W('bump', ['b', 'u', 'mp'], 51),
  W('itch', ['i', 'tch'], 51),
  W('malt', ['m', 'a', 'lt'], 51, undefined, [1]),
  W('salt', ['s', 'a', 'lt'], 51, '🧂', [1]),
  W('watch', ['w', 'a', 'tch'], 51, '⌚', [1]),
  // lesson 52
  W('jumping', ['j', 'u', 'mp', 'i', 'ng'], 52),
  W('camping', ['c', 'a', 'mp', 'i', 'ng'], 52, '🏕️'),
  W('helping', ['h', 'e', 'lp', 'i', 'ng'], 52),
  W('melting', ['m', 'e', 'lt', 'i', 'ng'], 52),
  W('catching', ['c', 'a', 'tch', 'i', 'ng'], 52),
  W('fetching', ['f', 'e', 'tch', 'i', 'ng'], 52),
  W('itching', ['i', 'tch', 'i', 'ng'], 52),
  W('chomp', ['ch', 'o', 'mp'], 52),
  W('chomping', ['ch', 'o', 'mp', 'i', 'ng'], 52),
  W('dump', ['d', 'u', 'mp'], 52),
  W('dumping', ['d', 'u', 'mp', 'i', 'ng'], 52),
  W('limping', ['l', 'i', 'mp', 'i', 'ng'], 52),
  W('yelping', ['y', 'e', 'lp', 'i', 'ng'], 52),
  W('filming', ['f', 'i', 'lm', 'i', 'ng'], 52),
  // lesson 53
  W('edge', ['e', 'dge'], 53),
  W('judge', ['j', 'u', 'dge'], 53, '🧑‍⚖️'),
  W('hodgepodge', ['h', 'o', 'dge', 'p', 'o', 'dge'], 53),
  W('lunge', ['l', 'u', 'nge'], 53),
  W('since', ['s', 'i', 'nce'], 53),
  W('rinse', ['r', 'i', 'nse'], 53),
  W('chance', ['ch', 'a', 'nce'], 53),
  W('budge', ['b', 'u', 'dge'], 53),
  W('fence', ['f', 'e', 'nce'], 53),
  // lesson 54
  W('dodge', ['d', 'o', 'dge'], 54),
  W('nudge', ['n', 'u', 'dge'], 54),
  W('dancing', ['d', 'a', 'nc', 'i', 'ng'], 54, '💃'),
  W('dense', ['d', 'e', 'nse'], 54),
  W('Madge', ['M', 'a', 'dge'], 54),
  // lesson 55
  W('blank', ['bl', 'a', 'nk'], 55),
  W('blend', ['bl', 'e', 'nd'], 55),
  W('broth', ['br', 'o', 'th'], 55, '🍲'),
  W('clam', ['cl', 'a', 'm'], 55),
  W('cloth', ['cl', 'o', 'th'], 55),
  W('clip', ['cl', 'i', 'p'], 55, '📎'),
  W('clump', ['cl', 'u', 'mp'], 55),
  W('cluck', ['cl', 'u', 'ck'], 55, '🐔'),
  W('crack', ['cr', 'a', 'ck'], 55),
  W('craft', ['cr', 'a', 'ft'], 55, '🎨'),
  W('crash', ['cr', 'a', 'sh'], 55, '💥'),
  W('crust', ['cr', 'u', 'st'], 55),
  // lesson 56
  W('after', ['a', 'f', 't', 'er'], 56),
  W('bathmat', ['b', 'a', 'th', 'm', 'a', 't'], 56),
  W('chopstick', ['ch', 'o', 'p', 'st', 'i', 'ck'], 56, '🥢'),
  W('contest', ['c', 'o', 'n', 't', 'e', 'st'], 56),
  W('dentist', ['d', 'e', 'n', 't', 'i', 'st'], 56),
  W('dustpan', ['d', 'u', 'st', 'p', 'a', 'n'], 56),
  W('finish', ['f', 'i', 'n', 'i', 'sh'], 56, '🏁'),
  W('sandwich', ['s', 'a', 'nd', 'w', 'i', 'ch'], 56, '🥪'),
  W('selfish', ['s', 'e', 'lf', 'i', 'sh'], 56),
  W('ridge', ['r', 'i', 'dge'], 56),
  W('wedge', ['w', 'e', 'dge'], 56),
  // lesson 57
  W('drop', ['dr', 'o', 'p'], 57, '💧'),
  W('drip', ['dr', 'i', 'p'], 57),
  W('drift', ['dr', 'i', 'ft'], 57),
  W('flap', ['fl', 'a', 'p'], 57),
  W('flat', ['fl', 'a', 't'], 57),
  W('flip', ['fl', 'i', 'p'], 57),
  W('flop', ['fl', 'o', 'p'], 57),
  W('fling', ['fl', 'i', 'ng'], 57),
  W('floss', ['fl', 'o', 'ss'], 57),
  W('fluff', ['fl', 'u', 'ff'], 57),
  W('flush', ['fl', 'u', 'sh'], 57, '🚽'),
  W('flex', ['fl', 'e', 'x'], 57, '💪'),
  W('Frank', ['Fr', 'a', 'nk'], 57),
  W('French', ['Fr', 'e', 'nch'], 57),
  // lesson 58
  W('drinks', ['dr', 'i', 'nk', 's'], 58, '🧃'),
  W('sandwiches', ['s', 'a', 'nd', 'w', 'i', 'ch', 'es'], 58),
  // lesson 59
  W('glitch', ['gl', 'i', 'tch'], 59),
  W('glum', ['gl', 'u', 'm'], 59, '😞'),
  W('glob', ['gl', 'o', 'b'], 59),
  W('grab', ['gr', 'a', 'b'], 59),
  W('grill', ['gr', 'i', 'll'], 59),
  W('grunt', ['gr', 'u', 'nt'], 59),
  W('plan', ['pl', 'a', 'n'], 59),
  W('plum', ['pl', 'u', 'm'], 59),
  W('plus', ['pl', 'u', 's'], 59, '➕'),
  W('plush', ['pl', 'u', 'sh'], 59, '🧸'),
  W('pluck', ['pl', 'u', 'ck'], 59),
  W('plug', ['pl', 'u', 'g'], 59, '🔌'),
  W('prank', ['pr', 'a', 'nk'], 59),
  // lesson 61
  W('slug', ['sl', 'u', 'g'], 61),
  W('slugs', ['sl', 'u', 'g', 's'], 61),
  W('slept', ['sl', 'e', 'pt'], 61, '😴'),
  W('shrink', ['shr', 'i', 'nk'], 61),
  W('shrug', ['shr', 'u', 'g'], 61, '🤷'),
  W('snug', ['sn', 'u', 'g'], 61),
  W('spend', ['sp', 'e', 'nd'], 61),
  W('spin', ['sp', 'i', 'n'], 61, '🌀'),
  W('spot', ['sp', 'o', 't'], 61),
  W('split', ['spl', 'i', 't'], 61),
  W('sprint', ['spr', 'i', 'nt'], 61, '🏃'),
  W('shrub', ['shr', 'u', 'b'], 61),
  W('sniff', ['sn', 'i', 'ff'], 61, '👃'),
  // lesson 62
  W('stack', ['st', 'a', 'ck'], 62, '📚'),
  W('stick', ['st', 'i', 'ck'], 62),
  W('sting', ['st', 'i', 'ng'], 62, '🐝'),
  W('stump', ['st', 'u', 'mp'], 62),
  W('swift', ['sw', 'i', 'ft'], 62),
  W('swing', ['sw', 'i', 'ng'], 62),
  W('scan', ['sc', 'a', 'n'], 62),
  W('skill', ['sk', 'i', 'll'], 62),
  W('skin', ['sk', 'i', 'n'], 62),
  W('scratch', ['scr', 'a', 'tch'], 62),
  W('scrap', ['scr', 'a', 'p'], 62),
  W('scrunch', ['scr', 'u', 'nch'], 62),
  W('skunks', ['sk', 'u', 'nk', 's'], 62, '🦨'),
  W('Scot', ['Sc', 'o', 't'], 62),
  // lesson 63
  W('splish', ['spl', 'i', 'sh'], 63),
  W('Gwen', ['Gw', 'e', 'n'], 63),
  W('I', ['I'], 63),
  // lesson 64
  W('track', ['tr', 'a', 'ck'], 64),
  W('trap', ['tr', 'a', 'p'], 64, '🪤'),
  W('trash', ['tr', 'a', 'sh'], 64, '🗑️'),
  W('trick', ['tr', 'i', 'ck'], 64, '🪄'),
  W('trim', ['tr', 'i', 'm'], 64, '✂️'),
  W('trot', ['tr', 'o', 't'], 64, '🐴'),
  W('trudge', ['tr', 'u', 'dge'], 64),
  W('trust', ['tr', 'u', 'st'], 64),
  W('twelve', ['tw', 'e', 'l', 'v', 'e'], 64),
  W('twig', ['tw', 'i', 'g'], 64),
  W('twigs', ['tw', 'i', 'g', 's'], 64),
  W('twitch', ['tw', 'i', 'tch'], 64),
  W('trek', ['tr', 'e', 'k'], 64, '🥾'),
  // lesson 65
  W('Greg', ['Gr', 'e', 'g'], 65),
  // lesson 66
  W('Jane', ['J', 'a_e', 'n'], 66),
  W('cape', ['c', 'a_e', 'p'], 66, '🦸'),
  // lesson 68
  W('ace', ['a_e', 'c'], 68),
  W('space', ['sp', 'a_e', 'c'], 68, '🌌'),
  W('fade', ['f', 'a_e', 'd'], 68),
  W('trade', ['tr', 'a_e', 'd'], 68, '🤝'),
  W('safe', ['s', 'a_e', 'f'], 68),
  W('age', ['a_e', 'g'], 68),
  W('stage', ['st', 'a_e', 'g'], 68, '🎭'),
  W('make', ['m', 'a_e', 'k'], 68),
  W('quake', ['qu', 'a_e', 'k'], 68),
  W('shake', ['sh', 'a_e', 'k'], 68),
  W('flame', ['fl', 'a_e', 'm'], 68, '🔥'),
  W('ape', ['a_e', 'p'], 68, '🦍'),
  W('shape', ['sh', 'a_e', 'p'], 68, '🔷'),
  W('take', ['t', 'a_e', 'k'], 68),
  // lesson 70
  W('braid', ['br', 'ai', 'd'], 70),
  W('nail', ['n', 'ai', 'l'], 70),
  W('jail', ['j', 'ai', 'l'], 70),
  W('quail', ['qu', 'ai', 'l'], 70),
  W('tail', ['t', 'ai', 'l'], 70),
  W('aim', ['ai', 'm'], 70, '🎯'),
  W('brain', ['br', 'ai', 'n'], 70, '🧠'),
  W('chain', ['ch', 'ai', 'n'], 70, '⛓️'),
  W('drain', ['dr', 'ai', 'n'], 70),
  W('grain', ['gr', 'ai', 'n'], 70, '🌾'),
  W('hair', ['h', 'ai', 'r'], 70),
  W('pair', ['p', 'ai', 'r'], 70),
  W('chair', ['ch', 'ai', 'r'], 70, '🪑'),
  W('bait', ['b', 'ai', 't'], 70),
  // lesson 71
  W('trail', ['tr', 'ai', 'l'], 71),
  W('asked', ['a', 'sk', 'e', 'd'], 71),
  // lesson 72
  W('hay', ['h', 'ay'], 72, '🌾'),
  W('lay', ['l', 'ay'], 72),
  W('may', ['m', 'ay'], 72),
  W('pay', ['p', 'ay'], 72),
  W('way', ['w', 'ay'], 72),
  W('clay', ['cl', 'ay'], 72),
  W('gray', ['gr', 'ay'], 72),
  W('tray', ['tr', 'ay'], 72),
  W('spray', ['spr', 'ay'], 72),
  W('stray', ['str', 'ay'], 72),
  W('hey', ['h', 'ey'], 72, '👋'),
  W('they', ['th', 'ey'], 72),
  W('obey', ['o', 'b', 'ey'], 72),
  W('Kay', ['K', 'ay'], 72),
  // lesson 74
  W('eighth', ['eigh', 'th'], 74),
  W('sleigh', ['sl', 'eigh'], 74, '🛷'),
  W('weigh', ['w', 'eigh'], 74, '⚖️'),
  W('weight', ['w', 'eigh', 't'], 74),
  W('rein', ['r', 'ei', 'n'], 74),
  W('vein', ['v', 'ei', 'n'], 74),
  W('veil', ['v', 'ei', 'l'], 74),
  W('their', ['th', 'ei', 'r'], 74),
  W('beige', ['b', 'ei', 'g', 'e'], 74),
  // lesson 75
  W('quails', ['qu', 'ai', 'l', 's'], 75),
  // lesson 76
  W('jaw', ['j', 'aw'], 76),
  W('lawn', ['l', 'aw', 'n'], 76),
  W('fawn', ['f', 'aw', 'n'], 76, '🦌'),
  W('straw', ['str', 'aw'], 76),
  W('sauce', ['s', 'au', 'c', 'e'], 76),
  W('pause', ['p', 'au', 's', 'e'], 76, '⏸️'),
  W('cause', ['c', 'au', 's', 'e'], 76),
  W('aunt', ['au', 'nt'], 76),
  W('fault', ['f', 'au', 'lt'], 76),
  W('vault', ['v', 'au', 'lt'], 76),
  // lesson 78
  W('mama', ['m', 'a', 'm', 'a'], 78, '👩'),
  W('papa', ['p', 'a', 'p', 'a'], 78, '👨'),
  W('father', ['f', 'a', 'th', 'er'], 78),
  W('arm', ['ar', 'm'], 78, '💪'),
  W('art', ['ar', 't'], 78, '🎨'),
  W('bark', ['b', 'ar', 'k'], 78),
  W('cart', ['c', 'ar', 't'], 78, '🛒'),
  W('charm', ['ch', 'ar', 'm'], 78),
  W('jar', ['j', 'ar'], 78, '🫙'),
  W('mark', ['m', 'ar', 'k'], 78),
  W('barn', ['b', 'ar', 'n'], 78),
  W('smart', ['sm', 'ar', 't'], 78),
  W('yarn', ['y', 'ar', 'n'], 78, '🧶'),
  W('start', ['st', 'ar', 't'], 78),
  // lesson 80
  W('war', ['w', 'ar'], 80),
  W('warm', ['w', 'ar', 'm'], 80),
  W('warmth', ['w', 'ar', 'm', 'th'], 80),
  W('warn', ['w', 'ar', 'n'], 80),
  W('swarm', ['sw', 'ar', 'm'], 80, '🐝'),
  W('quart', ['qu', 'ar', 't'], 80),
  W('dwarf', ['dw', 'ar', 'f'], 80),
  // lesson 81
  W('sip', ['s', 'i', 'p'], 81),
  // lesson 82
  W('bees', ['b', 'ee', 's'], 82, '🐝'),
  W('free', ['fr', 'ee'], 82),
  W('freeze', ['fr', 'ee', 'z', 'e'], 82),
  W('sneeze', ['sn', 'ee', 'z', 'e'], 82, '🤧'),
  W('feed', ['f', 'ee', 'd'], 82),
  W('need', ['n', 'ee', 'd'], 82),
  W('seed', ['s', 'ee', 'd'], 82, '🌱'),
  W('peek', ['p', 'ee', 'k'], 82),
  W('week', ['w', 'ee', 'k'], 82),
  W('cheek', ['ch', 'ee', 'k'], 82),
  W('eel', ['ee', 'l'], 82),
  W('wheel', ['wh', 'ee', 'l'], 82, '🛞'),
  W('cheese', ['ch', 'ee', 's', 'e'], 82, '🧀'),
  W('deer', ['d', 'ee', 'r'], 82, '🦌'),
  // lesson 86
  W('pea', ['p', 'ea'], 86, '🫛'),
  W('tea', ['t', 'ea'], 86, '🍵'),
  W('flea', ['fl', 'ea'], 86),
  W('each', ['ea', 'ch'], 86),
  W('teach', ['t', 'ea', 'ch'], 86),
  W('bead', ['b', 'ea', 'd'], 86, '📿'),
  W('real', ['r', 'ea', 'l'], 86),
  W('cream', ['cr', 'ea', 'm'], 86),
  W('ear', ['ea', 'r'], 86, '👂'),
  W('feast', ['f', 'ea', 'st'], 86),
  W('peace', ['p', 'ea', 'c', 'e'], 86),
  W('please', ['pl', 'ea', 's', 'e'], 86),
  // lesson 87
  W('here', ['h', 'e_e', 'r'], 87),
  W('scene', ['s', 'c', 'e_e', 'n'], 87),
  W('Steve', ['S', 't', 'e_e', 'v'], 87),
  W('there', ['th', 'e_e', 'r'], 87, undefined, [1]),
  W('where', ['wh', 'e_e', 'r'], 87, undefined, [1]),
  // lesson 90
  W('chief', ['ch', 'ie', 'f'], 90),
  W('thief', ['th', 'ie', 'f'], 90),
  W('field', ['f', 'ie', 'ld'], 90),
  W('shield', ['sh', 'ie', 'ld'], 90, '🛡️'),
  W('pier', ['p', 'ie', 'r'], 90),
  W('fierce', ['f', 'ie', 'r', 'c', 'e'], 90),
  W('niece', ['n', 'ie', 'c', 'e'], 90),
  W('piece', ['p', 'ie', 'c', 'e'], 90, '🧩'),
  // lesson 91
  W('fiend', ['f', 'ie', 'nd'], 91),
  W('wield', ['w', 'ie', 'ld'], 91),
  // lesson 92
  W('baby', ['b', 'a', 'b', 'y'], 92, '👶'),
  W('mommy', ['m', 'o', 'm', 'm', 'y'], 92, '👩'),
  W('daddy', ['d', 'a', 'dd', 'y'], 92, '👨'),
  W('puppy', ['p', 'u', 'p', 'p', 'y'], 92, '🐶'),
  W('bunny', ['b', 'u', 'n', 'n', 'y'], 92, '🐰'),
  W('sunny', ['s', 'u', 'n', 'n', 'y'], 92, '☀️'),
  W('silly', ['s', 'i', 'll', 'y'], 92, '🤪'),
  W('candy', ['c', 'a', 'nd', 'y'], 92, '🍬'),
  W('berry', ['b', 'e', 'r', 'r', 'y'], 92, '🫐'),
  W('cherry', ['ch', 'e', 'r', 'r', 'y'], 92, '🍒'),
  W('muddy', ['m', 'u', 'dd', 'y'], 92),
  W('messy', ['m', 'e', 'ss', 'y'], 92),
  W('sorry', ['s', 'o', 'r', 'r', 'y'], 92),
  W('easy', ['ea', 's', 'y'], 92),
  // lesson 94
  W('by', ['b', 'y'], 94),
  W('cry', ['cr', 'y'], 94, '😢'),
  W('dry', ['dr', 'y'], 94),
  W('fry', ['fr', 'y'], 94, '🍳'),
  W('shy', ['sh', 'y'], 94),
  W('spy', ['sp', 'y'], 94, '🕵️'),
  W('why', ['wh', 'y'], 94),
  W('lie', ['l', 'ie'], 94),
  W('guy', ['g', 'uy'], 94),
  // lesson 96
  W('ice', ['i_e', 'c'], 96, '🧊'),
  W('dice', ['d', 'i_e', 'c'], 96, '🎲'),
  W('mice', ['m', 'i_e', 'c'], 96, '🐭'),
  W('nice', ['n', 'i_e', 'c'], 96),
  W('rice', ['r', 'i_e', 'c'], 96, '🍚'),
  W('twice', ['tw', 'i_e', 'c'], 96),
  W('hide', ['h', 'i_e', 'd'], 96, '🙈'),
  W('side', ['s', 'i_e', 'd'], 96),
  W('wide', ['w', 'i_e', 'd'], 96),
  W('line', ['l', 'i_e', 'n'], 96),
  W('pine', ['p', 'i_e', 'n'], 96, '🌲'),
  W('fire', ['f', 'i_e', 'r'], 96, '🔥'),
  W('give', ['g', 'i_e', 'v'], 96, '🎁', [1]),
  W('live', ['l', 'i_e', 'v'], 96, undefined, [1]),
  // lesson 97
  W('geese', ['g', 'ee', 's', 'e'], 97, '🪿'),
  // lesson 98
  W('sigh', ['s', 'igh'], 98),
  W('fight', ['f', 'igh', 't'], 98),
  W('might', ['m', 'igh', 't'], 98),
  W('right', ['r', 'igh', 't'], 98),
  W('sight', ['s', 'igh', 't'], 98),
  W('tight', ['t', 'igh', 't'], 98),
  W('flight', ['fl', 'igh', 't'], 98, '✈️'),
  W('fright', ['fr', 'igh', 't'], 98, '😱'),
  // lesson 100
  W('Bonnie', ['B', 'o', 'n', 'n', 'ie'], 100),
  // lesson 101
  W('bought', ['b', 'ough', 't'], 101),
  W('brought', ['br', 'ough', 't'], 101),
  W('fought', ['f', 'ough', 't'], 101),
  W('thought', ['th', 'ough', 't'], 101, '💭'),
  W('taught', ['t', 'augh', 't'], 101),
  W('daughter', ['d', 'augh', 't', 'er'], 101, '👧'),
  W('rough', ['r', 'o', 'u', 'gh'], 101),
  W('tough', ['t', 'o', 'u', 'gh'], 101),
  W('cough', ['c', 'o', 'u', 'gh'], 101),
  W('coughing', ['c', 'o', 'u', 'gh', 'i', 'ng'], 101),
  W('laughing', ['l', 'au', 'gh', 'i', 'ng'], 101, '😂'),
  W('laughter', ['l', 'au', 'gh', 't', 'er'], 101),
  W('laughs', ['l', 'au', 'gh', 's'], 101),
  // lesson 102
  W('golden', ['g', 'o', 'ld', 'e', 'n'], 102),
  W('so', ['s', 'o'], 102),
  // lesson 103
  W('done', ['d', 'o_e', 'n'], 103),
  W('love', ['l', 'o_e', 'v'], 103, '❤️'),
  W('come', ['c', 'o_e', 'm'], 103),
  W('some', ['s', 'o_e', 'm'], 103),
  W('globe', ['gl', 'o_e', 'b'], 103, '🌍'),
  W('joke', ['j', 'o_e', 'k'], 103),
  W('broke', ['br', 'o_e', 'k'], 103),
  W('smoke', ['sm', 'o_e', 'k'], 103, '💨'),
  W('hole', ['h', 'o_e', 'l'], 103, '🕳️'),
  W('whole', ['wh', 'o_e', 'l'], 103),
  W('cone', ['c', 'o_e', 'n'], 103, '🍦'),
  W('phone', ['ph', 'o_e', 'n'], 103, '📱'),
  W('note', ['n', 'o_e', 't'], 103),
  W('store', ['st', 'o_e', 'r'], 103, '🏪'),
  // lesson 104
  W('go', ['g', 'o'], 104),
  W('campfire', ['c', 'a', 'mp', 'f', 'i_e', 'r'], 104, '🔥'),
  W('thick', ['th', 'i', 'ck'], 104),
  W('trees', ['tr', 'ee', 's'], 104, '🌳'),
  // lesson 105
  W('load', ['l', 'oa', 'd'], 105),
  W('road', ['r', 'oa', 'd'], 105, '🛣️'),
  W('toad', ['t', 'oa', 'd'], 105),
  W('oak', ['oa', 'k'], 105, '🌳'),
  W('loaf', ['l', 'oa', 'f'], 105, '🍞'),
  W('soap', ['s', 'oa', 'p'], 105, '🧼'),
  W('coat', ['c', 'oa', 't'], 105, '🧥'),
  W('float', ['fl', 'oa', 't'], 105),
  W('roar', ['r', 'oa', 'r'], 105),
  W('oar', ['oa', 'r'], 105),
  W('glow', ['gl', 'ow'], 105, '✨'),
  W('old', ['old'], 105, '👴'),
  W('cold', ['c', 'old'], 105, '🥶'),
  W('gold', ['g', 'old'], 105),
  // lesson 106
  W('coats', ['c', 'oa', 't', 's'], 106, '🧥'),
  // lesson 107
  W('could', ['c', 'ou', 'ld'], 107, undefined, [1, 2]),
  W('would', ['w', 'ou', 'ld'], 107, undefined, [1, 2]),
  W('should', ['sh', 'ou', 'ld'], 107, undefined, [1, 2]),
  W('couldn\'t', ['c', 'ou', 'ld', 'n\'t'], 107, undefined, [1, 2, 3]),
  W('wouldn\'t', ['w', 'ou', 'ld', 'n\'t'], 107, undefined, [1, 2, 3]),
  W('shouldn\'t', ['sh', 'ou', 'ld', 'n\'t'], 107, undefined, [1, 2, 3]),
  W('food', ['f', 'oo', 'd'], 107),
  W('moose', ['m', 'oo', 's', 'e'], 107, '🫎'),
  W('boot', ['b', 'oo', 't'], 107, '🥾'),
  W('tooth', ['t', 'oo', 'th'], 107, '🦷'),
  W('good', ['g', 'oo', 'd'], 107, '👍'),
  W('wood', ['w', 'oo', 'd'], 107, '🪵'),
  W('cook', ['c', 'oo', 'k'], 107),
  W('cookie', ['c', 'oo', 'k', 'ie'], 107, '🍪'),
  // lesson 108
  W('bit', ['b', 'i', 't'], 108),
  W('kids', ['k', 'i', 'd', 's'], 108),
  // lesson 109
  W('how', ['h', 'ow'], 109),
  W('now', ['n', 'ow'], 109),
  W('wow', ['w', 'ow'], 109),
  W('town', ['t', 'ow', 'n'], 109, '🏘️'),
  W('brown', ['br', 'ow', 'n'], 109, '🟤'),
  W('clown', ['cl', 'ow', 'n'], 109, '🤡'),
  W('crown', ['cr', 'ow', 'n'], 109, '👑'),
  W('towel', ['t', 'ow', 'e', 'l'], 109),
  W('tower', ['t', 'ow', 'er'], 109, '🗼'),
  W('flower', ['fl', 'ow', 'er'], 109, '🌸'),
  W('ouch', ['ou', 'ch'], 109),
  W('sound', ['s', 'ou', 'nd'], 109, '🔊'),
  W('house', ['h', 'ou', 's', 'e'], 109, '🏠'),
  W('mouse', ['m', 'ou', 's', 'e'], 109, '🐭'),
  // lesson 110
  W('touch', ['t', 'ou', 'ch'], 110),
  W('enough', ['e', 'n', 'ou', 'gh'], 110),
  W('four', ['f', 'ou', 'r'], 110),
  W('pour', ['p', 'ou', 'r'], 110, '🫗'),
  W('your', ['y', 'ou', 'r'], 110),
  W('fourth', ['f', 'ou', 'r', 'th'], 110),
  W('tour', ['t', 'ou', 'r'], 110),
  W('wound', ['w', 'ou', 'nd'], 110, '🩹'),
  // lesson 111
  W('joy', ['j', 'oy'], 111),
  W('oil', ['oi', 'l'], 111, '🛢️'),
  W('soil', ['s', 'oi', 'l'], 111),
  W('coil', ['c', 'oi', 'l'], 111),
  W('broil', ['br', 'oi', 'l'], 111),
  W('join', ['j', 'oi', 'n'], 111),
  W('point', ['p', 'oi', 'nt'], 111, '👉'),
  W('noise', ['n', 'oi', 's', 'e'], 111, '🔊'),
  W('voice', ['v', 'oi', 'c', 'e'], 111, '🗣️'),
  W('choice', ['ch', 'oi', 'c', 'e'], 111),
  W('annoy', ['a', 'n', 'n', 'oy'], 111),
  W('joyful', ['j', 'oy', 'f', 'u', 'l'], 111),
  // lesson 113
  W('Sue', ['S', 'ue'], 113),
  W('due', ['d', 'ue'], 113),
  W('clue', ['cl', 'ue'], 113),
  W('glue', ['gl', 'ue'], 113),
  W('true', ['tr', 'ue'], 113),
  W('fuel', ['f', 'ue', 'l'], 113, '⛽'),
  W('juice', ['j', 'ui', 'c', 'e'], 113, '🧃'),
  W('cruise', ['cr', 'ui', 's', 'e'], 113, '🛳️'),
  W('cube', ['c', 'u_e', 'b'], 113, '🧊'),
  W('tube', ['t', 'u_e', 'b'], 113),
  W('huge', ['h', 'u_e', 'g'], 113),
  W('rule', ['r', 'u_e', 'l'], 113),
  W('tune', ['t', 'u_e', 'n'], 113, '🎵'),
  W('spruce', ['spr', 'u_e', 'c'], 113, '🌲'),
  // lesson 114
  W('looks', ['l', 'oo', 'k', 's'], 114),
  W('like', ['l', 'i_e', 'k'], 114),
  // lesson 115
  W('dew', ['d', 'ew'], 115, '💧'),
  W('few', ['f', 'ew'], 115),
  W('news', ['n', 'ew', 's'], 115, '📰'),
  W('blew', ['bl', 'ew'], 115),
  W('brew', ['br', 'ew'], 115),
  W('chew', ['ch', 'ew'], 115),
  W('crew', ['cr', 'ew'], 115),
  W('drew', ['dr', 'ew'], 115),
  W('stew', ['st', 'ew'], 115, '🍲'),
  W('threw', ['thr', 'ew'], 115),
  W('view', ['v', 'i', 'ew'], 115),
  W('feud', ['f', 'eu', 'd'], 115),
  // lesson 116
  W('chirp', ['ch', 'ir', 'p'], 116),
  W('dirt', ['d', 'ir', 't'], 116),
  W('third', ['th', 'ir', 'd'], 116, '🥉'),
  W('fur', ['f', 'ur'], 116),
  W('burn', ['b', 'ur', 'n'], 116, '🔥'),
  W('hurt', ['h', 'ur', 't'], 116, '🤕'),
  W('purse', ['p', 'ur', 's', 'e'], 116, '👛'),
  W('nurse', ['n', 'ur', 's', 'e'], 116),
  W('learn', ['l', 'ear', 'n'], 116),
  W('pearl', ['p', 'ear', 'l'], 116),
  W('worm', ['w', 'or', 'm'], 116, '🪱'),
  W('birthday', ['b', 'ir', 'th', 'd', 'ay'], 116, '🎂'),
  W('turkey', ['t', 'ur', 'k', 'ey'], 116, '🦃'),
  W('turnip', ['t', 'ur', 'n', 'i', 'p'], 116),
  // lesson 117
  W('table', ['t', 'a', 'b', 'le'], 117),
  W('eagle', ['ea', 'g', 'le'], 117, '🦅'),
  W('bubble', ['b', 'u', 'b', 'b', 'le'], 117, '🫧'),
  W('fiddle', ['f', 'i', 'dd', 'le'], 117, '🎻'),
  W('simple', ['s', 'i', 'm', 'p', 'le'], 117),
  W('rustle', ['r', 'u', 's', 'tle'], 117),
  W('photo', ['ph', 'o', 't', 'o'], 117, '📷'),
  W('telephone', ['t', 'e', 'l', 'e', 'ph', 'o_e', 'n'], 117, '☎️'),
  W('graph', ['gr', 'a', 'ph'], 117, '📊'),
  // lesson 118
  W('treasure', ['tr', 'ea', 's', 'u', 'r', 'e'], 118, '💰'),
  W('measure', ['m', 'ea', 's', 'u', 'r', 'e'], 118, '📏'),
  W('picture', ['p', 'i', 'c', 't', 'u', 'r', 'e'], 118, '🖼️'),
  W('question', ['qu', 'e', 's', 'ti', 'o', 'n'], 118, '❓'),
  W('ferocious', ['f', 'e', 'r', 'o', 'ci', 'ou', 's'], 118),
  W('confusion', ['c', 'o', 'n', 'f', 'u', 'si', 'o', 'n'], 118),
  // lesson 119
  W('knee', ['kn', 'ee'], 119, '🦵'),
  W('knife', ['kn', 'i_e', 'f'], 119, '🔪'),
  W('knew', ['kn', 'ew'], 119),
  W('known', ['kn', 'ow', 'n'], 119),
  W('crumb', ['cr', 'u', 'mb'], 119),
  W('climb', ['cl', 'i', 'mb'], 119, '🧗'),
  W('debt', ['d', 'e', 'bt'], 119),
  W('hour', ['h', 'ou', 'r'], 119, '🕐'),
  W('ghost', ['gh', 'o', 'st'], 119, '👻'),
  W('rhyme', ['r', 'h', 'y', 'm', 'e'], 119),
  W('wrap', ['wr', 'a', 'p'], 119, '🎁'),
  W('wrong', ['wr', 'o', 'ng'], 119, '❌'),
  W('wrote', ['wr', 'o_e', 't'], 119),
  W('wreck', ['wr', 'e', 'ck'], 119),
  // lesson 120
  W('castle', ['c', 'a', 's', 'tle'], 120, '🏰'),
  W('whistle', ['wh', 'i', 's', 'tle'], 120),
  W('listen', ['l', 'i', 'st', 'e', 'n'], 120, '👂'),
  W('fasten', ['f', 'a', 'st', 'e', 'n'], 120),
  W('often', ['o', 'ft', 'e', 'n'], 120),
  W('school', ['s', 'ch', 'oo', 'l'], 120, '🏫'),
  W('choir', ['ch', 'oi', 'r'], 120),
  W('gym', ['g', 'y', 'm'], 120, '🏋️'),
  W('gymnast', ['g', 'y', 'm', 'n', 'a', 'st'], 120, '🤸'),
  W('mystery', ['m', 'y', 'st', 'e', 'r', 'y'], 120, '🕵️'),
];

export const WORDS_BY_ID: ReadonlyMap<string, Word> = new Map(WORDS.map((w) => [w.id, w]));

export function getWord(id: string): Word {
  const w = WORDS_BY_ID.get(id);
  if (!w) throw new Error(`Unknown word id: ${id}`);
  return w;
}
