import type { Word } from './types';

/**
 * Word bank for game levels 1–3 (book lessons 1–30).
 * Seeded from the photographed book pages; every word is decodable at its
 * `lesson` using only graphemes/memory words taught by then (validator-enforced).
 *
 * `emoji` is the picture revealed AFTER the word is decoded — never before.
 * Abstract words (has, and, was…) have no picture and only appear in
 * mechanics that don't need one.
 */

const W = (
  text: string,
  graphemes: string[],
  lesson: number,
  emoji?: string,
  heartIndexes?: number[],
): Word => ({
  id: text.toLowerCase(),
  text,
  graphemes,
  lesson,
  ...(emoji ? { emoji } : {}),
  ...(heartIndexes ? { heartIndexes } : {}),
});

export const WORDS: Word[] = [
  // ---- Level 1 · book lessons 1–9 (a + consonants) ----
  // The article "a" appears in book sentences from lesson 3 ("A man has a hat.")
  W('a', ['a'], 3),
  W('am', ['a', 'm'], 1),
  W('an', ['a', 'n'], 1),
  W('at', ['a', 't'], 1),
  W('ax', ['a', 'x'], 1, '🪓'),
  W('ant', ['a', 'n', 't'], 1, '🐜'),
  W('Sam', ['S', 'a', 'm'], 1, '👦'),
  W('sat', ['s', 'a', 't'], 1),
  W('mat', ['m', 'a', 't'], 1),
  W('man', ['m', 'a', 'n'], 1, '👨'),
  W('ham', ['h', 'a', 'm'], 2, '🍖'),
  W('hat', ['h', 'a', 't'], 2, '👒'),
  W('has', ['h', 'a', 's'], 2),
  W('Tam', ['T', 'a', 'm'], 2, '👧'),
  W('tax', ['t', 'a', 'x'], 2),
  W('as', ['a', 's'], 3),
  W('dad', ['d', 'a', 'd'], 4, '👨'),
  W('had', ['h', 'a', 'd'], 4),
  W('sad', ['s', 'a', 'd'], 4, '😢'),
  W('mad', ['m', 'a', 'd'], 4, '😠'),
  W('and', ['a', 'n', 'd'], 4),
  W('sand', ['s', 'a', 'n', 'd'], 4, '🏖️'),
  W('hand', ['h', 'a', 'n', 'd'], 4, '✋'),
  W('wax', ['w', 'a', 'x'], 4, '🕯️'),
  W('Max', ['M', 'a', 'x'], 4, '👦'),
  W('Dan', ['D', 'a', 'n'], 4, '👦'),
  W('dam', ['d', 'a', 'm'], 4),
  W('was', ['w', 'a', 's'], 5, undefined, [1]),
  W('lad', ['l', 'a', 'd'], 6, '👦'),
  W('land', ['l', 'a', 'n', 'd'], 6, '🏝️'),
  W('last', ['l', 'a', 's', 't'], 6),
  W('cat', ['c', 'a', 't'], 7, '🐱'),
  W('can', ['c', 'a', 'n'], 7, '🥫'),
  W('bat', ['b', 'a', 't'], 7, '🦇'),
  W('bag', ['b', 'a', 'g'], 7, '👜'),
  W('fan', ['f', 'a', 'n'], 7, '🪭'),
  W('fat', ['f', 'a', 't'], 7),
  W('jam', ['j', 'a', 'm'], 7, '🫙'),
  W('gas', ['g', 'a', 's'], 7, '⛽'),
  W('fast', ['f', 'a', 's', 't'], 7, '💨'),
  W('flag', ['f', 'l', 'a', 'g'], 7, '🚩'),
  W('pan', ['p', 'a', 'n'], 8, '🍳'),
  W('rat', ['r', 'a', 't'], 8, '🐀'),
  W('ran', ['r', 'a', 'n'], 8, '🏃'),
  W('van', ['v', 'a', 'n'], 8, '🚐'),
  W('map', ['m', 'a', 'p'], 8, '🗺️'),
  W('nap', ['n', 'a', 'p'], 8, '😴'),
  W('cap', ['c', 'a', 'p'], 8, '🧢'),
  W('lap', ['l', 'a', 'p'], 8),
  W('tap', ['t', 'a', 'p'], 8, '🚰'),
  W('rag', ['r', 'a', 'g'], 8),
  W('plant', ['p', 'l', 'a', 'n', 't'], 8, '🪴'),
  W('yak', ['y', 'a', 'k'], 9, '🐂'),
  W('yam', ['y', 'a', 'm'], 9, '🍠'),
  W('zap', ['z', 'a', 'p'], 9, '⚡'),
  W('ask', ['a', 's', 'k'], 9),
  W('mask', ['m', 'a', 's', 'k'], 9, '🎭'),

  // ---- Level 2 · book lessons 10–17 (doubles, ck/qu, e i o u) ----
  W('pass', ['p', 'a', 'ss'], 10),
  W('grass', ['g', 'r', 'a', 'ss'], 10, '🌿'),
  W('jazz', ['j', 'a', 'zz'], 10, '🎷'),
  W('add', ['a', 'dd'], 10, '➕'),
  W('pack', ['p', 'a', 'ck'], 11, '🎒'),
  W('back', ['b', 'a', 'ck'], 11),
  W('sack', ['s', 'a', 'ck'], 11, '🛍️'),
  W('black', ['b', 'l', 'a', 'ck'], 11, '⬛'),
  W('snack', ['s', 'n', 'a', 'ck'], 11, '🍿'),
  W('quack', ['qu', 'a', 'ck'], 11, '🦆'),
  W('bed', ['b', 'e', 'd'], 13, '🛏️'),
  W('red', ['r', 'e', 'd'], 13, '🟥'),
  W('fed', ['f', 'e', 'd'], 13),
  W('leg', ['l', 'e', 'g'], 13, '🦵'),
  W('hen', ['h', 'e', 'n'], 13, '🐔'),
  W('ten', ['t', 'e', 'n'], 13, '🔟'),
  W('pen', ['p', 'e', 'n'], 13, '🖊️'),
  W('net', ['n', 'e', 't'], 13, '🥅'),
  W('pet', ['p', 'e', 't'], 13, '🐹'),
  W('wet', ['w', 'e', 't'], 13, '💧'),
  W('vet', ['v', 'e', 't'], 13, '🧑‍⚕️'),
  W('jet', ['j', 'e', 't'], 13, '✈️'),
  W('yes', ['y', 'e', 's'], 13),
  W('get', ['g', 'e', 't'], 13),
  W('tell', ['t', 'e', 'll'], 13, '🗣️'),
  W('bell', ['b', 'e', 'll'], 13, '🔔'),
  W('well', ['w', 'e', 'll'], 13),
  W('egg', ['e', 'gg'], 13, '🥚'),
  W('nest', ['n', 'e', 's', 't'], 13, '🪺'),
  W('tent', ['t', 'e', 'n', 't'], 13, '⛺'),
  W('sit', ['s', 'i', 't'], 13, '🪑'),
  W('six', ['s', 'i', 'x'], 13, '6️⃣'),
  W('big', ['b', 'i', 'g'], 13),
  W('dig', ['d', 'i', 'g'], 13, '⛏️'),
  W('pig', ['p', 'i', 'g'], 13, '🐷'),
  W('wig', ['w', 'i', 'g'], 13, '💇'),
  W('win', ['w', 'i', 'n'], 13, '🏆'),
  W('fin', ['f', 'i', 'n'], 13, '🦈'),
  W('pin', ['p', 'i', 'n'], 13, '📌'),
  W('lip', ['l', 'i', 'p'], 13, '👄'),
  W('zip', ['z', 'i', 'p'], 13, '🤐'),
  W('hid', ['h', 'i', 'd'], 13),
  W('his', ['h', 'i', 's'], 13),
  W('him', ['h', 'i', 'm'], 13),
  W('in', ['i', 'n'], 13),
  W('is', ['i', 's'], 13),
  W('it', ['i', 't'], 13),
  W('if', ['i', 'f'], 13),
  W('ill', ['i', 'll'], 13, '🤒'),
  W('fix', ['f', 'i', 'x'], 13, '🔧'),
  W('mix', ['m', 'i', 'x'], 13, '🥣'),
  W('did', ['d', 'i', 'd'], 13),
  W('sick', ['s', 'i', 'ck'], 13, '🤒'),
  W('pick', ['p', 'i', 'ck'], 13),
  W('kick', ['k', 'i', 'ck'], 13, '⚽'),
  W('quick', ['qu', 'i', 'ck'], 13, '💨'),
  W('quit', ['qu', 'i', 't'], 13),
  W('quill', ['qu', 'i', 'll'], 13, '🪶'),
  W('hill', ['h', 'i', 'll'], 13, '⛰️'),
  W('will', ['w', 'i', 'll'], 13),
  W('Bill', ['B', 'i', 'll'], 13, '👦'),
  W('Jill', ['J', 'i', 'll'], 13, '👧'),
  W('miss', ['m', 'i', 'ss'], 13),
  W('kiss', ['k', 'i', 'ss'], 13, '💋'),
  W('milk', ['m', 'i', 'l', 'k'], 13, '🥛'),
  W('dog', ['d', 'o', 'g'], 14, '🐶'),
  W('log', ['l', 'o', 'g'], 14, '🪵'),
  W('fog', ['f', 'o', 'g'], 14, '🌫️'),
  W('jog', ['j', 'o', 'g'], 14, '🏃'),
  W('hot', ['h', 'o', 't'], 14, '🔥'),
  W('pot', ['p', 'o', 't'], 14, '🍲'),
  W('dot', ['d', 'o', 't'], 14, '🔴'),
  W('got', ['g', 'o', 't'], 14),
  W('not', ['n', 'o', 't'], 14),
  W('on', ['o', 'n'], 14),
  W('top', ['t', 'o', 'p'], 14, '🔝'),
  W('mop', ['m', 'o', 'p'], 14, '🧹'),
  W('hop', ['h', 'o', 'p'], 14, '🐇'),
  W('pop', ['p', 'o', 'p'], 14, '🎈'),
  W('box', ['b', 'o', 'x'], 14, '📦'),
  W('fox', ['f', 'o', 'x'], 14, '🦊'),
  W('ox', ['o', 'x'], 14, '🐂'),
  W('job', ['j', 'o', 'b'], 14),
  W('mom', ['m', 'o', 'm'], 14, '👩'),
  W('doll', ['d', 'o', 'll'], 14, '🪆'),
  W('sock', ['s', 'o', 'ck'], 14, '🧦'),
  W('rock', ['r', 'o', 'ck'], 14, '🪨'),
  W('lock', ['l', 'o', 'ck'], 14, '🔒'),
  W('bug', ['b', 'u', 'g'], 14, '🐛'),
  W('dug', ['d', 'u', 'g'], 14),
  W('mud', ['m', 'u', 'd'], 14, '🟤'),
  W('sun', ['s', 'u', 'n'], 14, '☀️'),
  W('run', ['r', 'u', 'n'], 14, '🏃'),
  W('fun', ['f', 'u', 'n'], 14, '🎉'),
  W('bun', ['b', 'u', 'n'], 14, '🥯'),
  W('cup', ['c', 'u', 'p'], 14, '☕'),
  W('cut', ['c', 'u', 't'], 14, '✂️'),
  W('nut', ['n', 'u', 't'], 14, '🥜'),
  W('hut', ['h', 'u', 't'], 14, '🛖'),
  W('but', ['b', 'u', 't'], 14),
  W('bus', ['b', 'u', 's'], 14, '🚌'),
  W('gum', ['g', 'u', 'm'], 14, '🍬'),
  W('hug', ['h', 'u', 'g'], 14, '🤗'),
  W('tub', ['t', 'u', 'b'], 14, '🛁'),
  W('cub', ['c', 'u', 'b'], 14, '🐻'),
  W('up', ['u', 'p'], 14, '⬆️'),
  W('us', ['u', 's'], 14),
  W('pup', ['p', 'u', 'p'], 14, '🐕'),
  W('duck', ['d', 'u', 'ck'], 14, '🦆'),
  W('luck', ['l', 'u', 'ck'], 14, '🍀'),
  W('truck', ['t', 'r', 'u', 'ck'], 14, '🚚'),
  W('jump', ['j', 'u', 'm', 'p'], 14, '🤸'),

  // ---- Level 3 · book lessons 18–30 (ph th sh ch wh + memory words) ----
  W('Phil', ['Ph', 'i', 'l'], 18, '👦'),
  W('Philip', ['Ph', 'i', 'l', 'i', 'p'], 18, '👦'),
  W('the', ['th', 'e'], 19, undefined, [1]),
  W('that', ['th', 'a', 't'], 19),
  W('than', ['th', 'a', 'n'], 19),
  W('them', ['th', 'e', 'm'], 19),
  W('then', ['th', 'e', 'n'], 19),
  W('this', ['th', 'i', 's'], 19),
  W('bath', ['b', 'a', 'th'], 19, '🛁'),
  W('path', ['p', 'a', 'th'], 19, '🛤️'),
  W('with', ['w', 'i', 'th'], 19),
  W('math', ['m', 'a', 'th'], 19, '➕'),
  W('thin', ['th', 'i', 'n'], 19),
  W('moth', ['m', 'o', 'th'], 19, '🦋'),
  W('Seth', ['S', 'e', 'th'], 19, '👦'),
  W('son', ['s', 'o', 'n'], 20, '👦', [1]),
  W('won', ['w', 'o', 'n'], 20, '🏆', [1]),
  W('of', ['o', 'f'], 20, undefined, [0, 1]),
  W('off', ['o', 'ff'], 20),
  W('deck', ['d', 'e', 'ck'], 20),
  W('put', ['p', 'u', 't'], 24, undefined, [1]),
  W('pull', ['p', 'u', 'll'], 24, undefined, [1]),
  W('push', ['p', 'u', 'sh'], 26, '🛒', [1]),
  W('ship', ['sh', 'i', 'p'], 26, '🚢'),
  W('shop', ['sh', 'o', 'p'], 26, '🏪'),
  W('shut', ['sh', 'u', 't'], 26, '🚪'),
  W('shed', ['sh', 'e', 'd'], 26, '🛖'),
  W('shell', ['sh', 'e', 'll'], 26, '🐚'),
  W('fish', ['f', 'i', 'sh'], 26, '🐟'),
  W('dish', ['d', 'i', 'sh'], 26, '🍽️'),
  W('wish', ['w', 'i', 'sh'], 26, '🌠'),
  W('rush', ['r', 'u', 'sh'], 26, '💨'),
  W('cash', ['c', 'a', 'sh'], 26, '💵'),
  W('dash', ['d', 'a', 'sh'], 26),
  W('wash', ['w', 'a', 'sh'], 26, '🧼', [1]),
  W('chin', ['ch', 'i', 'n'], 28, '🙂'),
  W('chop', ['ch', 'o', 'p'], 28, '🪓'),
  W('chat', ['ch', 'a', 't'], 28, '💬'),
  W('chest', ['ch', 'e', 's', 't'], 28, '🧰'),
  W('chick', ['ch', 'i', 'ck'], 28, '🐤'),
  W('much', ['m', 'u', 'ch'], 28),
  W('rich', ['r', 'i', 'ch'], 28, '💰'),
  W('such', ['s', 'u', 'ch'], 28),
  W('check', ['ch', 'e', 'ck'], 28, '✅'),
  W('when', ['wh', 'e', 'n'], 30),
  W('whip', ['wh', 'i', 'p'], 30),
  W('whiz', ['wh', 'i', 'z'], 30, '💫'),
  W('which', ['wh', 'i', 'ch'], 30),
  W('what', ['wh', 'a', 't'], 30, undefined, [1]),

  // ---- Story support (early-lesson words added for the story pages) ----
  W('fell', ['f', 'e', 'll'], 13),
  W('let', ['l', 'e', 't'], 13),
  W('lost', ['l', 'o', 's', 't'], 14),

  // ---- Level 4 · book lessons 31–45 (ng, nd/nt, er/nk/nch, ct/ft/pt/xt) ----
  // Lessons 31–34 review; clusters of taught single letters are decodable.
  W('crab', ['c', 'r', 'a', 'b'], 31, '🦀'),
  W('frog', ['f', 'r', 'o', 'g'], 31, '🐸'),
  W('swim', ['s', 'w', 'i', 'm'], 31, '🏊'),
  W('swam', ['s', 'w', 'a', 'm'], 31),
  W('drum', ['d', 'r', 'u', 'm'], 31, '🥁'),
  W('glad', ['g', 'l', 'a', 'd'], 31, '😊'),
  W('clap', ['c', 'l', 'a', 'p'], 31, '👏'),
  W('grin', ['g', 'r', 'i', 'n'], 31, '😁'),
  W('trip', ['t', 'r', 'i', 'p'], 31),
  W('brush', ['b', 'r', 'u', 'sh'], 31, '🪥'),
  W('splash', ['s', 'p', 'l', 'a', 'sh'], 31, '💦'),
  W('stop', ['s', 't', 'o', 'p'], 31, '🛑'),
  W('step', ['s', 't', 'e', 'p'], 31),
  W('sled', ['s', 'l', 'e', 'd'], 31, '🛷'),
  W('all', ['a', 'll'], 35, undefined, [0]),
  W('ring', ['r', 'i', 'ng'], 37, '💍'),
  W('king', ['k', 'i', 'ng'], 37, '🤴'),
  W('sing', ['s', 'i', 'ng'], 37, '🎤'),
  W('sang', ['s', 'a', 'ng'], 37),
  W('song', ['s', 'o', 'ng'], 37, '🎵'),
  W('long', ['l', 'o', 'ng'], 37),
  W('wing', ['w', 'i', 'ng'], 37, '🪽'),
  W('wand', ['w', 'a', 'nd'], 41, '🪄', [1]),
  W('want', ['w', 'a', 'nt'], 41, undefined, [1]),
  W('pond', ['p', 'o', 'nd'], 41),
  W('wind', ['w', 'i', 'nd'], 41, '💨'),
  W('end', ['e', 'nd'], 41),
  W('send', ['s', 'e', 'nd'], 41, '💌'),
  W('went', ['w', 'e', 'nt'], 41),
  W('mint', ['m', 'i', 'nt'], 41, '🍬'),
  W('pants', ['p', 'a', 'nt', 's'], 41, '👖'),
  W('her', ['h', 'er'], 43),
  W('sister', ['s', 'i', 's', 't', 'er'], 43, '👧'),
  W('winter', ['w', 'i', 'nt', 'er'], 43, '❄️'),
  W('summer', ['s', 'u', 'm', 'm', 'er'], 43, '☀️'),
  W('pink', ['p', 'i', 'nk'], 43, '🩷'),
  W('wink', ['w', 'i', 'nk'], 43, '😉'),
  W('drink', ['d', 'r', 'i', 'nk'], 43, '🥤'),
  W('thank', ['th', 'a', 'nk'], 43),
  W('lunch', ['l', 'u', 'nch'], 43, '🥪'),
  W('branch', ['b', 'r', 'a', 'nch'], 43),
  W('fern', ['f', 'er', 'n'], 43, '🌿'),
  W('gift', ['g', 'i', 'ft'], 45, '🎁'),
  W('soft', ['s', 'o', 'ft'], 45),
  W('left', ['l', 'e', 'ft'], 45, '⬅️'),
  W('lift', ['l', 'i', 'ft'], 45, '🏋️'),
  W('raft', ['r', 'a', 'ft'], 45, '🛶'),
  W('next', ['n', 'e', 'xt'], 45),
  W('fact', ['f', 'a', 'ct'], 45),

  // ---- Level 5 · book lessons 46–65 (final clusters, tch, dge/nce, blends) ----
  W('slip', ['sl', 'i', 'p'], 61),
  W('spell', ['sp', 'e', 'll'], 47, '✨'),
  W('spill', ['sp', 'i', 'll'], 47),
  W('stem', ['st', 'e', 'm'], 47, '🌱'),
  W('still', ['st', 'i', 'll'], 47),
  W('elk', ['e', 'lk'], 49, '🦌'),
  W('held', ['h', 'e', 'ld'], 49),
  W('elf', ['e', 'lf'], 49, '🧝'),
  W('shelf', ['sh', 'e', 'lf'], 49),
  W('golf', ['g', 'o', 'lf'], 49, '⛳'),
  W('calf', ['c', 'a', 'lf'], 49, '🐄', [1, 2]),
  W('half', ['h', 'a', 'lf'], 49, undefined, [1, 2]),
  W('talk', ['t', 'a', 'lk'], 49, '🗣️', [1, 2]),
  W('walk', ['w', 'a', 'lk'], 49, '🚶', [1, 2]),
  W('help', ['h', 'e', 'lp'], 51),
  W('melt', ['m', 'e', 'lt'], 51, '🫠'),
  W('belt', ['b', 'e', 'lt'], 51),
  W('lamp', ['l', 'a', 'mp'], 51, '🪔'),
  W('camp', ['c', 'a', 'mp'], 51, '🏕️'),
  W('stamp', ['st', 'a', 'mp'], 51, '📮'),
  W('catch', ['c', 'a', 'tch'], 51, '⚾'),
  W('patch', ['p', 'a', 'tch'], 51, '🩹'),
  W('fetch', ['f', 'e', 'tch'], 51, '🎾'),
  W('halt', ['h', 'a', 'lt'], 51, '✋', [1]),
  W('bridge', ['b', 'r', 'i', 'dge'], 53, '🌉'),
  W('badge', ['b', 'a', 'dge'], 53, '🎖️'),
  W('hedge', ['h', 'e', 'dge'], 53, '🌳'),
  W('fudge', ['f', 'u', 'dge'], 53, '🍫'),
  W('prince', ['p', 'r', 'i', 'nce'], 53, '🤴'),
  W('dance', ['d', 'a', 'nce'], 53, '💃'),
  W('one', ['o', 'n', 'e'], 53, '1️⃣', [0, 2]),
  W('once', ['o', 'nce'], 53, undefined, [0]),
  W('block', ['bl', 'o', 'ck'], 55),
  W('brick', ['br', 'i', 'ck'], 55, '🧱'),
  W('club', ['cl', 'u', 'b'], 55),
  W('clock', ['cl', 'o', 'ck'], 55, '🕐'),
  W('crunch', ['cr', 'u', 'nch'], 55),
  W('dress', ['dr', 'e', 'ss'], 57, '👗'),
  W('fresh', ['fr', 'e', 'sh'], 57),
  W('flash', ['fl', 'a', 'sh'], 57, '⚡'),
  W('frost', ['fr', 'o', 'st'], 57, '❄️'),
  W('glass', ['gl', 'a', 'ss'], 59),
  W('grand', ['gr', 'a', 'nd'], 59),
  W('print', ['pr', 'i', 'nt'], 59, '🖨️'),
  W('smell', ['sm', 'e', 'll'], 61, '👃'),
  W('snap', ['sn', 'a', 'p'], 61, '🫰'),
  W('spring', ['spr', 'i', 'ng'], 61, '🌸'),
  W('shrimp', ['shr', 'i', 'mp'], 61, '🦐'),
  W('string', ['str', 'i', 'ng'], 62, '🧵'),
  W('strong', ['str', 'o', 'ng'], 62, '💪'),
  W('skunk', ['sk', 'u', 'nk'], 62, '🦨'),
  W('skip', ['sk', 'i', 'p'], 62),
  W('scrub', ['scr', 'u', 'b'], 62, '🧽'),
  W('twin', ['tw', 'i', 'n'], 64, '👯'),
  W('twist', ['tw', 'i', 'st'], 64, '🌀'),
  W('thrill', ['thr', 'i', 'll'], 64, '🎢'),
  W('trunk', ['tr', 'u', 'nk'], 64, '🐘'),

  // ---- Level 6 · book lessons 66–77 (a_e, ai, ay, eigh, au/aw) ----
  W('cake', ['c', 'a_e', 'k'], 66, '🎂'),
  W('lake', ['l', 'a_e', 'k'], 66, '🏞️'),
  W('name', ['n', 'a_e', 'm'], 66),
  W('game', ['g', 'a_e', 'm'], 66, '🎲'),
  W('wave', ['w', 'a_e', 'v'], 66, '🌊'),
  W('snake', ['s', 'n', 'a_e', 'k'], 66, '🐍'),
  W('whale', ['wh', 'a_e', 'l'], 66, '🐋'),
  W('grape', ['g', 'r', 'a_e', 'p'], 66, '🍇'),
  W('brave', ['b', 'r', 'a_e', 'v'], 66),
  W('late', ['l', 'a_e', 't'], 66),
  W('bake', ['b', 'a_e', 'k'], 66, '🧁'),
  W('plate', ['p', 'l', 'a_e', 't'], 66, '🍽️'),
  W('gate', ['g', 'a_e', 't'], 66),
  W('ate', ['a_e', 't'], 66),
  W('made', ['m', 'a_e', 'd'], 66),
  W('are', ['a', 'r', 'e'], 66, undefined, [0, 2]),
  W('have', ['h', 'a', 'v', 'e'], 66, undefined, [3]),
  W('rain', ['r', 'ai', 'n'], 70, '🌧️'),
  W('sail', ['s', 'ai', 'l'], 70, '⛵'),
  W('snail', ['sn', 'ai', 'l'], 70, '🐌'),
  W('paint', ['p', 'ai', 'nt'], 70, '🎨'),
  W('wait', ['w', 'ai', 't'], 70),
  W('train', ['tr', 'ai', 'n'], 70, '🚂'),
  W('said', ['s', 'ai', 'd'], 70, undefined, [1]),
  W('again', ['a', 'g', 'ai', 'n'], 70, undefined, [0, 2]),
  W('against', ['a', 'g', 'ai', 'n', 'st'], 70, undefined, [0, 2]),
  W('day', ['d', 'ay'], 72),
  W('play', ['pl', 'ay'], 72, '🛝'),
  W('say', ['s', 'ay'], 72),
  W('stay', ['st', 'ay'], 72),
  W('away', ['a', 'w', 'ay'], 72, undefined, [0]),
  W('eight', ['eigh', 't'], 74, '8️⃣'),
  W('neigh', ['n', 'eigh'], 74, '🐴'),
  W('height', ['h', 'eigh', 't'], 74, '📏', [1]),
  W('paw', ['p', 'aw'], 76, '🐾'),
  W('saw', ['s', 'aw'], 76, '🪚'),
  W('draw', ['dr', 'aw'], 76, '🖍️'),
  W('yawn', ['y', 'aw', 'n'], 76, '🥱'),
  W('dawn', ['d', 'aw', 'n'], 76, '🌅'),
  W('hawk', ['h', 'aw', 'k'], 76, '🦅'),
  W('launch', ['l', 'au', 'nch'], 76, '🚀'),

  // ---- Level 7 · book lessons 78–95 (ar, ee, ea, e_e, ie, y-as-vowel, uy) ----
  W('star', ['st', 'ar'], 80, '⭐'),
  W('car', ['c', 'ar'], 80, '🚗'),
  W('far', ['f', 'ar'], 80),
  W('farm', ['f', 'ar', 'm'], 80, '🚜'),
  W('shark', ['sh', 'ar', 'k'], 80, '🦈'),
  W('dark', ['d', 'ar', 'k'], 80, '🌑'),
  W('park', ['p', 'ar', 'k'], 80, '🌳'),
  W('card', ['c', 'ar', 'd'], 80, '🃏'),
  W('see', ['s', 'ee'], 82, '👀'),
  W('bee', ['b', 'ee'], 82, '🐝'),
  W('tree', ['tr', 'ee'], 82, '🌳'),
  W('feet', ['f', 'ee', 't'], 82, '🦶'),
  W('green', ['gr', 'ee', 'n'], 82, '🟩'),
  W('sleep', ['sl', 'ee', 'p'], 82, '😴'),
  W('sheep', ['sh', 'ee', 'p'], 82, '🐑'),
  W('queen', ['qu', 'ee', 'n'], 82, '👸'),
  W('sweet', ['sw', 'ee', 't'], 82, '🍭'),
  W('three', ['thr', 'ee'], 82, '3️⃣'),
  W('been', ['b', 'ee', 'n'], 84, undefined, [1]),
  W('she', ['sh', 'e'], 84, undefined, [1]),
  W('he', ['h', 'e'], 84, undefined, [1]),
  W('be', ['b', 'e'], 84, undefined, [1]),
  W('we', ['w', 'e'], 84, undefined, [1]),
  W('me', ['m', 'e'], 84, undefined, [1]),
  W('sea', ['s', 'ea'], 86, '🌊'),
  W('eat', ['ea', 't'], 86, '😋'),
  W('read', ['r', 'ea', 'd'], 86, '📖'),
  W('beach', ['b', 'ea', 'ch'], 86, '🏖️'),
  W('leaf', ['l', 'ea', 'f'], 86, '🍃'),
  W('peach', ['p', 'ea', 'ch'], 86, '🍑'),
  W('dream', ['dr', 'ea', 'm'], 86, '💭'),
  W('clean', ['cl', 'ea', 'n'], 86, '🧼'),
  W('Pete', ['P', 'e_e', 't'], 87, '👦'),
  W('these', ['th', 'e_e', 's'], 87),
  W('pie', ['p', 'ie'], 90, '🥧'),
  W('tie', ['t', 'ie'], 90, '👔'),
  W('cried', ['cr', 'ie', 'd'], 90, '😢'),
  W('tried', ['tr', 'ie', 'd'], 90),
  // Lesson 92 is y-as-vowel; 'y' the grapheme is taught, the sound is new.
  W('my', ['m', 'y'], 92),
  W('fly', ['fl', 'y'], 92, '🪰'),
  W('sky', ['sk', 'y'], 92, '🌌'),
  W('try', ['tr', 'y'], 92),
  W('happy', ['h', 'a', 'p', 'p', 'y'], 92, '😄'),
  W('funny', ['f', 'u', 'n', 'n', 'y'], 92, '😂'),
  W('buy', ['b', 'uy'], 94, '🛍️'),

  // ---- Level 8 · book lessons 96–115 (i_e, igh, o_e, oa/ow, oo, ou, oy/oi, ue/ui/u_e, ew) ----
  W('smile', ['sm', 'i_e', 'l'], 96, '😊'),
  W('bike', ['b', 'i_e', 'k'], 96, '🚲'),
  W('kite', ['k', 'i_e', 't'], 96, '🪁'),
  W('time', ['t', 'i_e', 'm'], 96, '⏰'),
  W('five', ['f', 'i_e', 'v'], 96, '5️⃣'),
  W('ride', ['r', 'i_e', 'd'], 96, '🐎'),
  W('shine', ['sh', 'i_e', 'n'], 96, '🌟'),
  W('night', ['n', 'igh', 't'], 98, '🌙'),
  W('light', ['l', 'igh', 't'], 98, '💡'),
  W('high', ['h', 'igh'], 98),
  W('bright', ['br', 'igh', 't'], 98, '✨'),
  W('laugh', ['l', 'augh'], 101, '🤣'),
  W('caught', ['c', 'augh', 't'], 101),
  W('home', ['h', 'o_e', 'm'], 103, '🏠'),
  W('bone', ['b', 'o_e', 'n'], 103, '🦴'),
  W('nose', ['n', 'o_e', 's'], 103, '👃'),
  W('rose', ['r', 'o_e', 's'], 103, '🌹'),
  W('rope', ['r', 'o_e', 'p'], 103, '🪢'),
  W('hope', ['h', 'o_e', 'p'], 103),
  W('boat', ['b', 'oa', 't'], 105, '🛥️'),
  W('goat', ['g', 'oa', 't'], 105, '🐐'),
  W('snow', ['sn', 'ow'], 105, '☃️'),
  W('slow', ['sl', 'ow'], 105, '🐢'),
  W('yellow', ['y', 'e', 'll', 'ow'], 105, '🟨'),
  W('rainbow', ['r', 'ai', 'n', 'b', 'ow'], 105, '🌈'),
  W('moon', ['m', 'oo', 'n'], 107, '🌕'),
  W('book', ['b', 'oo', 'k'], 107, '📚'),
  W('spoon', ['sp', 'oo', 'n'], 107, '🥄'),
  W('look', ['l', 'oo', 'k'], 107, '👀'),
  W('zoo', ['z', 'oo'], 107, '🦓'),
  W('out', ['ou', 't'], 109),
  W('cloud', ['cl', 'ou', 'd'], 109, '☁️'),
  W('shout', ['sh', 'ou', 't'], 109, '📣'),
  W('found', ['f', 'ou', 'nd'], 109),
  W('loud', ['l', 'ou', 'd'], 109, '🔊'),
  W('cow', ['c', 'ow'], 109, '🐄'),
  W('doubt', ['d', 'ou', 'bt'], 110, undefined, [2]),
  W('boy', ['b', 'oy'], 111, '👦'),
  W('toy', ['t', 'oy'], 111, '🧸'),
  W('coin', ['c', 'oi', 'n'], 111, '🪙'),
  W('blue', ['bl', 'ue'], 113, '🟦'),
  W('fruit', ['fr', 'ui', 't'], 113, '🍉'),
  W('cute', ['c', 'u_e', 't'], 113, '🥰'),
  W('mule', ['m', 'u_e', 'l'], 113, '🫏'),
  W('new', ['n', 'ew'], 115),
  W('flew', ['fl', 'ew'], 115),
  W('grew', ['gr', 'ew'], 115),
  W('through', ['thr', 'ough'], 115, undefined, [1]),
  W('sew', ['s', 'ew'], 115, '🪡', [1]),

  // ---- Level 9 · book lessons 116–120 (r-vowels, le/tle, ci/ti/si, silent letters) ----
  W('bird', ['b', 'ir', 'd'], 116, '🐦'),
  W('girl', ['g', 'ir', 'l'], 116, '👧'),
  W('corn', ['c', 'or', 'n'], 116, '🌽'),
  W('fork', ['f', 'or', 'k'], 116, '🍴'),
  W('turn', ['t', 'ur', 'n'], 116),
  W('earth', ['ear', 'th'], 116, '🌍'),
  W('little', ['l', 'i', 't', 'tle'], 117),
  W('apple', ['a', 'p', 'p', 'le'], 117, '🍎'),
  W('purple', ['p', 'ur', 'p', 'le'], 117, '🟪'),
  W('turtle', ['t', 'ur', 'tle'], 117, '🐢'),
  W('candle', ['c', 'a', 'nd', 'le'], 117, '🕯️'),
  W('special', ['sp', 'e', 'ci', 'a', 'l'], 118),
  W('lamb', ['l', 'a', 'mb'], 119, '🐑'),
  W('write', ['wr', 'i_e', 't'], 119, '✍️'),
  W('knight', ['kn', 'igh', 't'], 119, '🛡️'),
];

export const WORDS_BY_ID: ReadonlyMap<string, Word> = new Map(WORDS.map((w) => [w.id, w]));

export function getWord(id: string): Word {
  const w = WORDS_BY_ID.get(id);
  if (!w) throw new Error(`Unknown word id: ${id}`);
  return w;
}
